### ISSUE TITLE
Server returning `null` after creating a data file with an extension

### ISSUE THREAD

**Issue by mertkahyaoglu** [jekyll/jekyll-admin#104]

**Comment by benbalter** [comment]
@mertkahyaoglu sorry about that. Do you have an example cURL that can recreate this? We have a test in place that ensures the response, but digging in now.

**Comment by mertkahyaoglu** [comment]
Here it is `curl -X PUT -d '{"test":"test"}' http://localhost:4000/_api/data/test10.yml`

**Comment by mertkahyaoglu** [comment]
@benbalter Ah, got it now, it should not have a file extension 😬

**Comment by benbalter** [comment]
Got it. Yep, the issue is the `.yml` extension, which means the server isn't following the spec. I'll get a fix up momentarily, as you should be passing the extension in the event it's a JSON file, which is also supported.

**Comment by mertkahyaoglu** [comment]
Yeah, but it creates a data file like test10.yml.yml

**Comment by benbalter** [comment]
https://github.com/jekyll/jekyll-admin/pull/107 Should allow the server to accept data files with and without an extension.

**Comment by mertkahyaoglu** [comment]
Nice 👍
