### ISSUE TITLE
Ability to read/write CSV data files

### ISSUE THREAD

**Issue by benbalter** [jekyll/jekyll-admin#108]
Similar to https://github.com/jekyll/jekyll-admin/issues/106, this would allow the API to read, write and delete CSV data files in the `_data` folder, which Jekyll supports.

**Comment by mertkahyaoglu** [comment]
@benbalter Doesn't the API support reading/writing CSV/JSON/YAML data files right now ? If the front end sends the content of the data files as it is with `raw_content`, it will write to the disk without converting to any other format. ([source code](https://github.com/jekyll/jekyll-admin/blob/master/lib/jekyll-admin/server/data.rb#L38))
