### ISSUE TITLE
API Datafile PUT response

### ISSUE THREAD

**Issue by mertkahyaoglu** [jekyll/jekyll-admin#110]
Right now, after a PUT request `curl -X PUT -d '{"test":"test"}'`, server responds with;

```
{"test":"test"}
```

Is it possible to include the filename here ? Like this;

```
{
  "file_name": {
     "test":"test"
  }
}
```

So users are redirected to the created datafile page looking to the response filename.

**Comment by benbalter** [comment]
Data files aren't currently objects in Jekyll (see https://github.com/jekyll/jekyll/issues/5207), but we can implement that behavior ourselves.

**Comment by benbalter** [comment]
@mertkahyaoglu Can you explain a bit more what you're trying to solve for? If you're making a `PUT` request to `/data/filename.yml`, a get request to that same endpoint would return the file (or is it that you want the object to know it's own filename so it can be passed around more easily?)

**Comment by mertkahyaoglu** [comment]
> you want the object to know it's own filename so it can be passed around more easily

That was my aim. I got a messy solution but it's OK for now.

**Comment by benbalter** [comment]
Slightly larger technical lift because it's not a native object in Jekyll land, but have a solution in the works.
