### ISSUE TITLE
Setting a post path to a future date returns error

### ISSUE THREAD

**Issue by mertkahyaoglu** [jekyll/jekyll-admin#112]
For example, while this request is OK;

`curl -X PUT -d '{ "body": "test" }' http://localhost:4000/_api/collections/posts/2016-08-07-test.md`

this one returns error;

`curl -X PUT -d '{ "body": "test" }' http://localhost:4000/_api/collections/posts/2017-08-07-test.md`

**Comment by benbalter** [comment]
I *suspect* we need to enable `future: true` regardless of the settings config to instruct Jekyll to read in future posts.

**Comment by benbalter** [comment]
`curl -X PUT -d '{ "body": "test" }' http://localhost:4000/_api/collections/posts/2016-08-07-test.md`

@mertkahyaoglu FWIW, this works for me now, but suspect that's for different reasons :smile:

**Comment by mertkahyaoglu** [comment]
@benbalter Ops, false alarm then 😂

**Comment by benbalter** [comment]
> false alarm then

Guess my joke was lost over the internet. It was resolved because *today* that date is no longer in the future. :smile:

**Comment by mertkahyaoglu** [comment]
No, I got it, I was developing your joke 😂
