### ISSUE TITLE
Release v0.1.0

### ISSUE THREAD

**Issue by benbalter** [jekyll/jekyll-admin#128]
The time has come for Jekyll Admin's [initial release](https://github.com/jekyll/jekyll-admin/milestone/1).

Here's my list of what needs to be done:

- [x] Update documentation
- [x] @mertkahyaoglu registers a rubygems.org account if he doesn't have one
- [x] Create `script/release` to build static site and release (#131)
- [x] Confirm Gem contents are what we want
- [x] Consider moving `lib/jekyll-admin/public/` to root to combine metadata files (#130)
  - [x] Combine docs
  - [x] Update build location
  - [x] Update source location

@mertkahyaoglu on the last checkbox, what do you think about moving `lib/jekyll-admin/public/`'s files to the root (so that we'd have `/src`, `/tools`, etc.). We'd then build to `lib/jekyll-admin/public/` and the site would use that as its root, instead of `lib/jekyll-admin/public/dist`? I think that makes more sense from a project structure standpoint, so that metadata files like `.editorconfig` can live in the repo root, especially as this project becomes open source, and not just a GSoC project.

More broadly, does the above list make sense? Anything else we're missing? Hoping, if you feel comfortable with where things are at, we can release a v0.1. to Rubygems either late this week or early next week?

**Comment by mertkahyaoglu** [comment]
> what do you think about moving lib/jekyll-admin/public/'s files to the root

Yeah, this makes sense 👍  But what about common files like `readme.md`, `license`, `.gitignore` ? We need to merge them somehow.

**Comment by benbalter** [comment]
> We need to merge them somehow.

Yep. That's my suggestion. I *think* those should be the only three, and should be easy enough to manually merge. If you start a PR to move things around such that the site is built to the `public` dir (rather than `/public/dist`) I can update the server in that same PR.

**Comment by benbalter** [comment]
See https://github.com/jekyll/jekyll-admin/issues/136 for pre-release testing instructions.
