### ISSUE TITLE
Renaming a post does not update the url

### ISSUE THREAD

**Issue by Crunch09** [jekyll/jekyll-admin#137]
Steps to reproduce:
* Go to `/admin/collections/posts` 
* Click on a post, change the title and save

What i expected:
* The URL would update

What happened:
* The URL didn't update
* A reload of the site throws a 404
* After this on `/admin/collections/posts` the message `Something gone wrong.` is shown until i fully reload the site.

<img width="492" alt="screen shot 2016-08-18 at 22 43 44" src="https://cloud.githubusercontent.com/assets/570608/17790075/4108700e-6595-11e6-9beb-66ecdb07046b.png">

**Comment by mertkahyaoglu** [comment]
Thanks for the issue, @Crunch09.

@benbalter Do we need to redirect to the new url when the path changes? 
To me, it is not necessary since the url does not effect your following actions and for a single page app, reloading makes no sense for me. But of course, if it bothers you, I would love to implement that.

That error is because you are trying to access to the post that does not exists anymore and the error message is not cleared until another action. We are going to get rid of those silly messages soon. I'm working on a notification system to be able to handle errors better.

**Comment by benbalter** [comment]
> and for a single page app, reloading makes no sense for me

Maybe down the line if Jekyll Admin were hosted, someone might email a URL to a colleague, but for now, you're right? If it's not hard to implement, and it doesn't have to be for the final release, it'd be a nice bit of polish to update the URL/history. Would that affect forward/back behavior as well?

**Comment by mertkahyaoglu** [comment]
Yeah, that might be a case. I will look into this.

**Comment by frankis** [comment]
Maybe I am getting it wrong, but if there is a URL change for a post/page that´s been live/published previously I would suggest that i.e. feeds and sitemap are recreated (if not by default anyway) to reflect any changes.

In addition, the /admin config maybe could allow utilizing a redirect plugin or using something like [this](https://superdevresources.com/redirects-jekyll-github-pages/) - SEO everywhere :) 

A "real" 301 would be a nightmare to implement - apart from server variations to cover, the required write access for /admin will be a no go for most people anyway.

**Comment by benbalter** [comment]
>  I would suggest that i.e. feeds and sitemap are recreated (if not by default anyway) to reflect any changes.

Any time JekyllAdmin makes a write operation, it triggers a rebuild, so sitemaps and themes should update.

**Comment by benbalter** [comment]
> In addition, the /admin config maybe could allow utilizing a redirect plugin or using something like this - SEO everywhere :)

Since JekyllAdmin runs locally, I'm not sure that SEO considerations are relevant here, unless I'm misunderstanding?

**Comment by frankis** [comment]
> Since JekyllAdmin runs locally, I'm not sure that SEO considerations are relevant here, unless I'm misunderstanding?

As one may edit existing posts/pages with JekyllAdmin (existing = been published before) a change of those posts/pages slug or title would effect the sites URL and therefore affect SEO - a lot.
