### ISSUE TITLE
Creating a New Metadata Field Doesn't Automatically Create A Valid Field Name, Or Indicate the User Can

### ISSUE THREAD

**Issue by budparr** [jekyll/jekyll-admin#139]
When a user adds a "New meta-data field" they should 
1) not have to rename the field by default, and 
2) it should be intuitive that there's a way to do so, and
3) the field should instruct them how to make a valid field name, or not allow them to make an invalid field.

The current view (screenshot attached) creates an invalid field name by default (e.g. `New Field 14`), and there's no way of telling that the user can click into the box to edit it, nor is there any way to enforce or instruct them to use a proper field name.

<img width="564" alt="screen shot 2016-08-18 at 7 44 48 pm" src="https://cloud.githubusercontent.com/assets/115347/17794357/b78cb6a4-657c-11e6-8f6a-5e28c15204bd.png">

**Comment by quinns** [comment]
Agreed, I was stumped by this too.
