### ISSUE TITLE
i18n supported?

### ISSUE THREAD

**Issue by frankis** [jekyll/jekyll-admin#143]
Hi there

Will i18n supported in the front end on release?
(sorry to ask, I am still struggling getting /admin to work on a nitrous.io - if i18n isn´t supported, I can stop investigating / troubleshooting)

**Comment by benbalter** [comment]
@frankis can you explain a bit more about what you're trying to do, what you're expecting, and what's actually happening?

**Comment by frankis** [comment]
I am just keen to know if JekyllAdmin supports maintaining Pots/Pages/DataSets in more than one language from the FrontEnd. I couldn't find any related information.

**Comment by benbalter** [comment]
Jekyll itself doesn't support that, as far as I know. If you implemented your own, or a third party solution, as long as the files were on disk, it should be compatible.
