### ISSUE TITLE
Trying to create a data file without a file name zeros out the file content

### ISSUE THREAD

**Issue by benbalter** [jekyll/jekyll-admin#145]
### Steps to reproduce

1. Navigate to http://localhost:4000/admin/datafile/new
2. Enter content in the file content body textarea box
3. Click save
4. Get an error that you need to add a file name

### Expected

Textarea retains content, allowing me to add a filename and re-save

### Actuall

😢 I lost all that data I just spent hours entering

**Comment by mertkahyaoglu** [comment]
Woaw, that's bad 👎
