### ISSUE TITLE
Pages endpoint should only return files that render to HTML

### ISSUE THREAD

**Issue by benbalter** [jekyll/jekyll-admin#151]
e.g., it should exclude `.scss` and `.coffee` files, which are technically pages in Jekyll's eyes, but are not pages from a user's perspective. 

We might want to go even further and limit it to markdown files, or at least disable the markdown editor for non-markdown files.

Or, if we wanted to do less, explicitly blacklist `.scss` and `.coffee` files.

**Comment by DirtyF** [comment]
If you only wanna show pages, you might want to blacklist common files like `robots.txt`, `humans.txt`, `feed.xml` or `manifest.json`

**Comment by DirtyF** [comment]
Also + 💯  for decoupling UI from the filesystem, and provide people task-based entries, like `Themes`, `Styles` or `Scripts`.
