### ISSUE TITLE
Reloading after deleting file

### ISSUE THREAD

**Issue by rush-skills** [jekyll/jekyll-admin#16]
I have been trying to implement the `DELETE /pages/:pageid` route and whenever I deleted a page, I was getting `ERROR Errno::ENOENT: No such file or directory @ rb_sysopen - <page>.md` when I tried to open the index route. This was due to the `@site` instance not being updated with the latest list of pages. Any idea how can I get around this? @parkr

**Comment by rush-skills** [comment]
This also affects changes in frontmatter - if the permalink is changed, the page is still accessible on the old permalink and inaccessible on the new one.

**Comment by benbalter** [comment]
@rush-skills I believe you'll want to call `Site#reset` and `Site#read` to re-read the site back in. Alternatively, you could manually remove the page from `Site#pages` to save the reload.

**Comment by parkr** [comment]
@rush-skills Yep, Ben has the right idea. A more efficient way of doing this would be simply `@site.pages.delete_if { |p| p.relative_path == "<page>.md" }`, but doing a full `@site.process` would rebuild the preview site too.

**Comment by rush-skills** [comment]
@benbalter @parkr Thanks! I guess that should solve the delete problem. How about the case where we update a page and its frontmatter? The behaviour right now is that the content is updated but the permalink remains the same.

**Comment by parkr** [comment]
> How about the case where we update a page and its frontmatter? The behaviour right now is that the content is updated but the permalink remains the same.

For `POST /pages/:pageid`? In that case, re-running `site.process` and using the `page.to_liquid.to_json` should be fine. In the UI, if a page is updated and the page ID changes, then it should redirect the user back to the main listing of pages and tell them that a page with that ID no longer exists.

**Comment by rush-skills** [comment]
@parkr Thanks, running site.process worked for pages and collections. It still however doesn't update the configuration data: the file is changed and the updated file re-read and shown in the api, but the site is unchanged, because it requires a server restart to reload configuration.
