### ISSUE TITLE
FrontMatter defaults aren´t applied when creating new posts or pages

### ISSUE THREAD

**Issue by frankis** [jekyll/jekyll-admin#161]
Currently creating new posts or pages seem not reflect FrontMatter defaults set in _config.yml

Expected behavior:
Creating new posts or pages should apply FrontMatter defaults by default in order to allow creating "templates" for "post-types" holding the default meta / Frontmatter information as specified such as "date", "tags", "layout" or "author".

**Comment by benbalter** [comment]
@frankis I'm not quite sure what behavior you're expecting here. If I have a front matter default of `foo: bar` in my config, and I create a new post, I don't want the `foo: bar` to also be hard coded into the front matter of the post on save. If the post is saved without that front matter, it should be properly read in by Jekyll when rendered.

**Comment by benbalter** [comment]
Closing this in favor of https://github.com/jekyll/jekyll-admin/issues/165, which I believe is the same thing.
