### ISSUE TITLE
Feature Request: Option to hide specific files from being displayed.

### ISSUE THREAD

**Issue by frankis** [jekyll/jekyll-admin#162]
Currently main.scss is shown as part of pages.

Expected behavior:
Show only (html, md,...) within pages in order to avoid confusion for editors using JeykllAdmin.
Rather than hiding any non html by default, there should be a config setting allowing to hide enable/disbale files to be shown OR create a new category for system files as well as styles and scripts and have related files shown there (maybe a tabbed sections within configuration?)

**Comment by benbalter** [comment]
Thanks for this. Would https://github.com/jekyll/jekyll-admin/issues/151 meet your expectations?

**Comment by benbalter** [comment]
Closing in favor of #151, which I believe should solve this.
