### ISSUE TITLE
Initial release

### ISSUE THREAD

**Issue by christoga** [jekyll/jekyll-admin#168]
> Disclaimer : Initial release will not be available before 23th August 2016. Meanwhile you can install jekyll-admin locally.

Isn't today is 23th August 2016?

```
ERROR:  Could not find a valid gem 'jekyll-admin' (>= 0) in any repository
```

**Comment by mertkahyaoglu** [comment]
We are going to release it today if nothing goes wrong. Be patient please :smiley:

**Comment by christoga** [comment]
I didn't mean to be rude tho. Thank's for the reply

**Comment by mertkahyaoglu** [comment]
Not at all. It's good to see that people can't wait its release 😄

**Comment by christoga** [comment]
HYPE! HYPE! HYPE!
