### ISSUE TITLE
Don't show time in post list if time is 12:00AM

### ISSUE THREAD

**Issue by benbalter** [jekyll/jekyll-admin#173]
A nice usability tweak, in my mind, there are two types of users:
1. Those that add times to all their posts
2. Those that never add times to their post

The first ones, obviously, want to see the time on the post list. For the second group, it's just cruft. I think it's safe to assume if a post is posted at exactly 12:00AM, it either didn't have a time, or is intended to be for the whole day (and thus the time can be hidden).

Alternatively, we can actually look to see if a time is specified, but I'm not sure how complicated that would be given the current data model.

**Comment by envygeeks** [comment]
This idea is leads to bad UX.

**Comment by benbalter** [comment]
> This idea is leads to bad UX.

Not displaying the time when the user hasn't specified one, or displaying it?

Also to note, a related issue, dates and times are shown for collections without dates and times.

**Comment by envygeeks** [comment]
I might be grasping the idea wrong but hiding the date is bad UX. It should
always be there if it is ever there.

**Comment by benbalter** [comment]
There are two issues:

1. Showing/hiding the date *per collection*:

  1. Posts, which have dates, should have their date displayed. That's a no brainer.
  2. Puppies, which never have dates, shouldn't have today's date displayed for all documents (as it does today).

2. Showing/hiding the time *per document*:

  1. If the Document has a date of `2016-01-01` in the filename, we should display that as the date, not `2016-01-01 12:00AM` as it does today.

  2. If the document has `date: 2016-01-01 12:35PM` in the front matter, we should display the full date + time.

**Comment by Joshfindit** [comment]
Question to @benbalter - Since specifying time is not mandatory, it seems the logical course of action is to show the time when it's specified, and not show it when it's not.

Am I mis-understanding?

**Comment by benbalter** [comment]
> Since specifying time is not mandatory, it seems the logical course of action is to show the time when it's specified, and not show it when it's not.

Yep. That's what I was trying to suggest. Thanks for articulating it better. :smile:

**Comment by mertkahyaoglu** [comment]
@benbalter To achieve this, we might look at the document's front matter whether it contains date attribute. If it does, we show the time. But since index endpoints do not have front matter, this option is not doable.

The second way is that we check if the time is exactly `00:00:00` with some regex and show it in post list accordingly.

**Comment by Joshfindit** [comment]
@mertkahyaoglu How about this:

- If the frontmatter specifies `date: YYYY-MM-DD HH:MM` (with or without `SS` or `+/-TTTT`), show time
- If the frontmatter specifies `date: YYYY-MM-DD`, do not show time

**Comment by mertkahyaoglu** [comment]
@Joshfindit Yeah, that was what I was thinking. But as I said, the front end cannot access the documents` front matter in post list. This was our design choice to make index endpoints minimal by removing the unused keys.
