### ISSUE TITLE
Can't edit posts if no title present

### ISSUE THREAD

**Issue by miklb** [jekyll/jekyll-admin#176]
In addition to regular articles, I also have, let's call them notes, that are title-less microblog posts.

Therefore the link to edit is on an empty anchor and not clickable (tested in Safari Tech Preview & Firefox).

Not sure of a solution, perhaps putting anchor on the `<td>` instead.

**Comment by mertkahyaoglu** [comment]
@benbalter Isn't `title` auto-generated from `filename` for documents?

Otherwise, `title` || `filename` should fix this.

**Comment by benbalter** [comment]
> Isn't title auto-generated from filename for documents?

Yep. (1) the front end won't let you create a post without a title, and (2) if done via command line, it pulls the title from the filename.

@miklb can you describe the steps we can take to reproduce your issue?

**Comment by miklb** [comment]
@benbalter This was tested on an existing project with existing content.

Here is [an example post](https://github.com/miklb/jekyll-indieweb/blob/master/_posts/2016-07-14-25279.md) demonstrating the type of post referenced.

So to replicate, if you were to add that post to `_posts`, you will see the anchor tag is empty and not clickable in the `<td>` for Title. 

If you need more background on how the post is generated or I can answer any other questions just holler.

**Comment by benbalter** [comment]
I'm having trouble recreating this. I created a new post `/_posts/2016-05-01-1234.md` and was able to access it from `/admin/posts`:

### The UI

![screen shot 2016-08-24 at 1 13 24 pm](https://cloud.githubusercontent.com/assets/282759/17940352/ab0d62a0-69fc-11e6-8c30-6d029d977f27.png)

### The API

![screen shot 2016-08-24 at 1 13 29 pm](https://cloud.githubusercontent.com/assets/282759/17940351/ab04f390-69fc-11e6-9cb6-a3874763d63b.png)

@miklb if I'm understanding correctly, you're saying there's no text where I have "1234" for you to click?

**Comment by benbalter** [comment]
Ohhhhhh. I see what's going on there.

I suspect the issue is that `""` is truthy in Javascript. We need to be looking at (in pseudo code) `title.empty? ? slug : title` not `title || slug`.

**Comment by miklb** [comment]
That makes sense. The micropub endpoint that generates these posts adds the `""` but I could look at omitting the quotes in the Front Matter template.

**Comment by mertkahyaoglu** [comment]
@benbalter Actually it is truthy-falsy. The problem is there is [no check](https://github.com/jekyll/jekyll-admin/blob/master/src/containers/views/Documents.js#L73) for title being empty. Front-end assumes that title will never be empty since it is auto-generated from filename. So relying on that, I just put title in there.

**Comment by mertkahyaoglu** [comment]
> The micropub endpoint that generates these posts adds the ""

Yeah, if it is putting `title: ""` into the front matter, that will override the one generated from filename. Therefore the link will be empty.

**Comment by miklb** [comment]
But I don't want a title generated. I explicitly want the title to be empty.

**Comment by mertkahyaoglu** [comment]
I'm creating a PR for this. @benbalter Which one do you prefer;

1. `title || (slug+ext)`
2. `title || (slug)`

**Comment by benbalter** [comment]
> But I don't want a title generated. I explicitly want the title to be empty.

Can you explain a bit more about what you're doing there? I almost want to say the current behavior is then the expected behavior, if you're telling Jekyll not to give this post a title.

**Comment by miklb** [comment]
These are micropub notes, e.g. a Tweet that originates on the site and then syndicated to Twitter. (Or any other other social media silo). They are not intended to have a title.

If the expected behavior is that every post must explicitly have a title, that's fine, but I'm not unique in my use case.

**Comment by miklb** [comment]
Some background on [micropub](http://indieweb.org/micropub) and [notes](http://indieweb.org/notes)

**Comment by DirtyF** [comment]
@miklb thanks for mentioning micropub, [it's now a W3C standard](https://www.w3.org/TR/micropub/).

**Comment by miklb** [comment]
@DirtyF it's getting there, and the recent announcement is a big step. When I first saw jekyll-admin, micropub seemed like a perfect fit. But off topic for this issue 😉

**Comment by DirtyF** [comment]
@benbalter FWIW here is an exemple of notes (posts without a title - replaced by the publication date): https://adactio.com/notes/
