### ISSUE TITLE
JSON::ParserError - 784: unexpected token

### ISSUE THREAD

**Issue by mdxprograms** [jekyll/jekyll-admin#183]
Describe in one or two sentences why you're opening this issue:

### Tell us a bit about yourself

* Version of JekyllAdmin I'm using (hint: use `bundle show` to check): jekyll-admin (0.1.0)
* Version of Jekyll I'm using (hint: use `bundle show` to check): jekyll (3.2.1)
* Operating System (e.g. OS X, Windows): OS X
* Browser (e.g, Safari, Chrome): Chrome

### Steps to reproduce

List the steps someone else can take to reproduce the conditions you're reporting:

1. `bundle exec jekyll s`
2. navigate to: `http://127.0.0.1:4000/admin/configuration`
3. change a value and click `save`

### Expected

After you take those steps, what are you expecting to happen?

To save my configuration updates after clicking on the save button.

### Actual

After you take those steps, what actually happens?

JSON::ParserError

### Other details

```
JSON::ParserError - 784: unexpected token at '"title: Your awesome title\nemail: your-email@domain.com\ndescription: >\n  Write an awesome description for your new site here. You can edit this line in\n  _config.yml. It will appear in your document head meta (for Google search\n  results) and in your feed.xml site description.\nbaseurl: ''\nurl: ''\ntwitter_username: jekyllrb\ngithub_username: jekyll\nmarkdown: kramdown\ntheme: minima\n"':
```

**Comment by DirtyF** [comment]
Same behavior here. `jekyll doctor` says everything looks fine.

**Comment by benbalter** [comment]
It looks like we're trying to parse YAML as JSON, possibly [on this line](https://github.com/jekyll/jekyll-admin/blob/master/lib/jekyll-admin/server.rb#L45), which is called via [this line](https://github.com/jekyll/jekyll-admin/blob/master/lib/jekyll-admin/server/configuration.rb#L36-L39).

@mertkahyaoglu do you recall if the configuration sends JSON or YAML? I suspect we'll want it to send the raw YAML? If so, this is an API bug. If on the other hand, we want all endpoints to talk JSON, and have the front end return YAML in a `raw_content` field, I think that'd be more consistent with other endpoints, and would be a bit more flexible down the line.

**Comment by benbalter** [comment]
Oh, and @mdxprograms thanks for reporting! 😄

**Comment by mertkahyaoglu** [comment]
Wow. That's my silly mistake. I forgot to update [this line](https://github.com/jekyll/jekyll-admin/blob/master/src/actions/config.js#L31) after implementing notification system. It should be `JSON.stringify(json)`. PR is on the way 🚀

**Comment by mdxprograms** [comment]
@benbalter @mertkahyaoglu thanks for taking a look! 👍

**Comment by mertkahyaoglu** [comment]
Thanks for reporting @mdxprograms 👍
