### ISSUE TITLE
Jekyll fails and data disappear on post invalid date.

### ISSUE THREAD

**Issue by codegaze** [jekyll/jekyll-admin#187]
Describe in one or two sentences why you're opening this issue:

### Steps to reproduce

Add a post path with a 2016-55-55.md (by mistake or boredom) date and save. 

### Expected

Show an error of invalid post path or something and continue working.

### Actual

A message "could not update the document" appears and all the data disappear from the admin (jekyll fails'

At my terminal I get 

```
Error: Invalid date '2016-55-55': Document '_posts/2016-55-55-title.md' does not have a valid date in the filename.
Error: Run jekyll build --trace for more `information.`
```
I have to delete the .md file manual to make Jekyll work again.

### Other details

I believe this can be solved by a small validation refactoring :blush:

**Comment by mertkahyaoglu** [comment]
@codegaze I can't reproduce this. Front end should be validating posts` paths. (You can take a look at the code [here](https://github.com/jekyll/jekyll-admin/blob/master/src/utils/validation.js))

Here what I get after an invalid post path.

![screen shot 2016-08-25 at 11 28 35 pm](https://cloud.githubusercontent.com/assets/7414026/17984864/d71674d4-6b1b-11e6-9c88-73017fb52df9.png)

**Comment by mertkahyaoglu** [comment]
@codegaze Ah, the problem occurs if you try to add a document of a non-post collection, right? I see it now.

**Comment by codegaze** [comment]
Ooops sorry, forgot to add the .md extention. Updated the initial issue

**Comment by mertkahyaoglu** [comment]
>  forgot to add the .md extention

It's still catching it for me. Are you having the issue with `posts` documents or other collections' documents? Because, yeah, there is a missing validation for non-post documents. I'm creating a fix right now.

**Comment by codegaze** [comment]
This is an issue with posts. Haven't tested this with other collections. Also forgot to mention I am using the official 0.1.0 Jekyll Admin Gem and Jekyll 3.2.1.

This is what I am getting after save:
![ja-error-1](https://cloud.githubusercontent.com/assets/7371227/17986023/612596f0-6b21-11e6-8882-937c60d71e17.png)

This may help as it assures the date is valid.  (only tested in chrome console with success)

 `const DATE_FILENAME_MATCHER = /^(?:.+\/)*(\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1]))-(.*)(\.[^.]+)$/` .

**Comment by mertkahyaoglu** [comment]
Yep, got it. Thanks for the regex. It's working great 👍

**Comment by codegaze** [comment]
@mertkahyaoglu  Anytime! :sunny: Do you believe a test separation for date and the rest of the filename will resolve to better validation messages to the user? Of course this needs some work to identify most of the cases.

e.g.

- '2016-02-02'
 - You need to append your title to the filename.
 - You need to specify a file extension to the filename.
- 'my-title'
 - You need to specify a date to the filename.
 - You need to specify a file extension to the filename.
- '2017-22-22-my-title.md'
 - You need to specify a valid date to the filename.

**Comment by mertkahyaoglu** [comment]
That would be a really nice polish ✨  but as you said it needs some work which shouldn't be our priority for the initial release. (It should be very straightforward with the current validation system though since validations are easily expandable).

**Comment by codegaze** [comment]
I 'll keep testing but if there is anything else I can help on the front-end, do tell! :wink:
