### ISSUE TITLE
Allow Jekyll Admin UI on live sites

### ISSUE THREAD

**Issue by andrewbanchich** [jekyll/jekyll-admin#190]
Would it be possible to allow Jekyll Admin to work on live sites so that less tech savvy people can update their blogs? I wonder if this can be done by allowing users to log in with GitHub so that there doesn't need to be any databases or user authentication on Jekyll's end. That way, we'd also be able to tie it in to our GitHub repos directly instead of updating our sites locally and then pushing to GitHub or our other host.

**Comment by benbalter** [comment]
> Could that be done more easily if GitHub used Docker containers to run Jekyll Pages like GitLab does?

Not that I see. Lets say you spun up a Heroku instance and put Jekyll on it and cloned down your site. You're still left with three problems:

1. The server Jekyll ships with isn't really intended to serve production traffic.

2. You'd need to have one instance per repo, which doesn't really scale.

3. Jekyll Admin would be writing content to disk on the Heroku instance (or Docker container in your example).  You'd need to figure out how to get that content back to the GItHub repo.

**Comment by andrewbanchich** [comment]
Okay thanks!

**Comment by borisrorsvort** [comment]
can we assume the project is going in the direction of https://forestry.io/ or http://www.siteleaf.com/ ?

**Comment by benbalter** [comment]
> can we assume the project is going in the direction of https://forestry.io/ or http://www.siteleaf.com/ ?

For now, at least, we're working on refining the user experience of local site administration, building towards a solid 1.0.

**Comment by luowei** [comment]
Looking forward to local site administration ，admin password protected auth ...
