### ISSUE TITLE
Add deployment docs/stategies

### ISSUE THREAD

**Issue by borisrorsvort** [jekyll/jekyll-admin#196]
In order to allow clients to update the site without installing locally, what would the setup?
Is there something missing? Shall it be a milestone?

**Comment by mertkahyaoglu** [comment]
Whoops. Was checking our milestones.

We have #75 for this. The site publishing is not available right now but will be implemented in the future. It's in the [nice-to-have milestone](https://github.com/jekyll/jekyll-admin/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Nice+to+have%22) which is for cool features that we are planning to implement in the future.

**Comment by borisrorsvort** [comment]
Ok thanks. Despite the great work, I don't see how this project will be useful without being hosted somewhere (#75). Or am I missing something?

**Comment by mertkahyaoglu** [comment]
@borisrorsvort Please see #190 for more information.
