### ISSUE TITLE
Whereabouts are the discussions/specifications for this project

### ISSUE THREAD

**Issue by georgemoon** [jekyll/jekyll-admin#20]
Hi there,

I was just looking into doing something like this for a personal project when I found this. 
I appreciate it's early days, but are there any specifications/documentation on what this project is ultimately aiming to do?

Thanks

**Comment by parkr** [comment]
@georgemoon Very cool! While public, this is being worked on by our GSoC students and we have to ensure they are able to complete their pieces. See [my post on jekyllrb.com](http://jekyllrb.com/news/2016/06/03/update-on-jekyll-s-google-summer-of-code-projects/) for more information about what we're aiming to do. 😄 

@benbalter We could probably include the API spec here, too, eh?

**Comment by georgemoon** [comment]
Awesome, I look forward to seeing what is achieved in a couple of months. Thanks for the quick response.
