### ISSUE TITLE
Broken links to xml files when using JekyllFeed plugin

### ISSUE THREAD

**Issue by ashmaroli** [jekyll/jekyll-admin#202]
Describe in one or two sentences why you're opening this issue:

> Broken-links to .xml files when using JekyllFeed plugin
### Tell us a bit about yourself
- Version of JekyllAdmin I'm using <hint: use `bundle show` to check>: **_0.1.0**_
- Version of Jekyll I'm using <hint: use `bundle show` to check>: **_[Jekyll Repo at this commit](https://github.com/jekyll/jekyll/tree/58cd8f3f4e29df5cb2c6ec62fa95ea3969d90fba)**_
- Operating System <e.g. OS X, Windows>: **_Windows 7**_
- Browser <e.g, Safari, Chrome>: **_Chrome**_
### Steps to reproduce

`bundle exec jekyll serve`
Navigate to /admin
Try viewing/editing any of the XML files listed
### Expected

Expected the contents of the file accessed, to be served.
### Actual

JekyllAdmin's version of 404 error
### Other details

The commit is part of yet-to-be-released version of Jekyll. So plenty of time to roll-in a fix for this issue.

**Comment by benbalter** [comment]
> Try viewing/editing any of the XML files listed

Is this on the site created by `jekyll new`? Are you adding the JekyllFeed plugin to an existing site? Running Jekyll on an empty directory shouldn't contain any XML files.

> The commit is part of yet-to-be-released version of Jekyll. So plenty of time to roll-in a fix for this issue.

Are you able to recreate the issue using the last stable (released) version? If so, can you describe the change on `master` that would cause this?

**Comment by ashmaroli** [comment]
> can you describe the change on master that would cause this?

Yes, This [PR](https://github.com/jekyll/jekyll/pull/5196/files) you proposed.

> Are you able to recreate the issue using the last stable (released) version?

No, the released version has the .xml at the root of the blog. So its totally accessible. The reason it fails in the future-release of jekyll is that with the commit, a subsequent generated new blog will not have .xml in the root but will be sourced from the plugin. But Jekyll-admin doesnt respect the change in the location of the .xml
Both .xml files are shown in the \pages. Only, they're nt accessible. 

### screenshot of /pages of a site generated with Jekyll3.2.1

![pages](https://cloud.githubusercontent.com/assets/12479464/18054079/0f02ba9a-6e20-11e6-987e-61e3bfebca0a.png)

- feed.xml is accessible.
- main.scss is not.

### screenshot of /pages of a site generated with that commit **_incorporated into jekyll.3.2.1_**

![eagle eyes](https://cloud.githubusercontent.com/assets/12479464/18054210/8a4adc82-6e20-11e6-8d6b-c44f8ecaa25e.png)

- Both the .xml files are inaccessible. (Returns '..not found..' error)
- main.scss is not accessible either.

**Comment by mertkahyaoglu** [comment]
With #210, only the files that render to HTML are listed in pages.
