### ISSUE TITLE
Bug Report - 29/08/2016

### ISSUE THREAD

**Issue by ashmaroli** [jekyll/jekyll-admin#203]
## Bug report - 29082016:
_The bugs mentioned below have been identified on a ***Windows 7*** machine running the **master branch of jekyll/jekyll-admin** and **jekyll 3.2.1** with **the latest versions of Ruby, NodeJS** and  **npm.**_

### /page/new 
- if an example.txt is created, it gets listed under /pages instead of under /staticfiles. There is no information that tells a user that this interface is to be used only for creating markdown pages nor any validation if he tries to create a .txt file or .html file. example.txt created above though has the frontmatter dashes inserted.
- when the above example.txt is renamed to example.md, the flash notification shows an error message, but the file is renamed anyway.

### /staticfiles
- when a user tries to upload an image file, a corrupted version of the same is created at the root instead. (tested with .jpg, .png)
- when a user tries to upload a .rb file (why? for research purposes), the file is created at root successfully, though a newline is inserted after every existing original line.

**Comment by benbalter** [comment]
@ashmaroli Thanks for these descriptive bug reports. Very helpful. Would you mind opening individual issues for each bug you found so that they are easier to track and assign?
