### ISSUE TITLE
PageCreate can create .txt file but treats it like a .md file

### ISSUE THREAD

**Issue by ashmaroli** [jekyll/jekyll-admin#204]
### Describe in one or two sentences why you're opening this issue:

I'm new to JekyllAdmin and had no idea that Create New Page should be used to create only markdown documents. Moreover the plugin did not stop me from creating a .txt file.
### Tell us a bit about yourself
- Version of JekyllAdmin I'm using <hint: use `bundle show` to check>: 0.1.0
- Version of Jekyll I'm using <hint: use `bundle show` to check>: 3.2.1
- Operating System <e.g. OS X, Windows>: Windows 7
- Browser <e.g, Safari, Chrome>: Chrome
### Steps to reproduce

Navigate to `http://localhost:3000/admin/page/new`
create demo.txt by entering that in the breadcrumb
Navigate up one level to http://localhost:3000/admin/page
### Expected

Expected demo.txt to not be listed there.
Expected demo.txt to be listed at /staticfiles.
### Actual

demo.txt is listed at /pages
### Other details
- There is no clear indication that tells a user, that this interface is to be used only for creating markdown pages nor any validation if he tries to create a .txt file or .html file. 
- demo.txt created above has the frontmatter dashes inserted.

**Comment by benbalter** [comment]
@ashmaroli to confirm, you created a new page via `page/new`, and you expect it to show up in `staticfiles`, not `pages`? Can you explain a bit more why you expect that? If you created as a new page, shouldn't it be a page? (Pages can have any extension).

**Comment by ashmaroli** [comment]
> Can you explain a bit more why you expect that?

Just for this issue, lets assume, I'm a totally green novice user. ***Hence started this ticket with:***
>I'm new to JekyllAdmin and had no idea that Create New Page should be used to create only markdown documents.

**Comment by ashmaroli** [comment]
Thats how I learned how the plugin differentiates between a page and a static file.
Frontmatter? then Page, else static file.

**Comment by ashmaroli** [comment]
Firstly, I need you to consider this as a bug/a shortcoming within the plugin rather than a rare catch by a novice user.
Secondly, this bug can be fixed by either of the foll.:
 - validating the file extension of the new file to be created. Support only markdown extensions
 - Lock the front end to accept only the filename (w/o extns) and assign a ***.md*** internally (complex solution)

**Comment by mertkahyaoglu** [comment]
@ashmaroli Just tested this and I think this is fixed in v0.2.0. I don't know how though 😬

**Comment by mertkahyaoglu** [comment]
Closed via #307
