### ISSUE TITLE
New posts lack metadata fields

### ISSUE THREAD

**Issue by dougmckown** [jekyll/jekyll-admin#207]
**New posts lack Layout, Date, and Categories fields.**

* Version of JekyllAdmin I'm using <hint: use `bundle show` to check>: 0.1.0
* Version of Jekyll I'm using <hint: use `bundle show` to check>: 3.2.1
* Operating System <e.g. OS X, Windows>: OS X 10.11.6
* Browser <e.g, Safari, Chrome>: Safari 9.1.2

### Steps to reproduce

Create a new post  

### Expected

I expected to see three fields at the bottom of the new post: Layout, Date, and Categories

### Actual

Now posts have do not have these fields (Layout, Date, and Categories). When I view the new post, it has no styling. I assume that this is because I can't set the Layout field to Posts.

**Comment by benbalter** [comment]
@dougmckown it sounds like you're talking about https://github.com/jekyll/jekyll-admin/issues/165? The idea that the editor should have certain blank fields by default that the user is prompted to fill out?

**Comment by dougmckown** [comment]
Yes, that's it. Sorry for the duplicate.
