### ISSUE TITLE
Keeping a todo feature/fix list suggestion

### ISSUE THREAD

**Issue by codegaze** [jekyll/jekyll-admin#208]
:bulb: Maybe there should be a todo list kept by the main maintainers, with the difficulty of each todo item(maybe organized into back and front end), to inform contributors about the current project's needs or how urgent a bug fix is. :smiley:

**Comment by DirtyF** [comment]
@codegaze Aren't issues, labels and milestones made for that?  https://github.com/jekyll/jekyll-admin/milestones ?

**Comment by codegaze** [comment]
Point taken @DirtyF

**Comment by DirtyF** [comment]
@codegaze to be fair that does not mean that the current roadmap milestones answer your question. 

I'm pretty confident that @benbalter and @mertkahyaoglu will tag issues and add more milestones in order to give a glimpse of what's next for `jekyll-admin`. 

Would `easy-pick` or ★, ★★, ★★★ labels help?

**Comment by codegaze** [comment]
Any documented label would help contributors understand the difficulty of each issue. :wink:

**Comment by benbalter** [comment]
@codegaze great question. [The `help-wanted` label](https://github.com/jekyll/jekyll-admin/issues?q=is%3Aissue+is%3Aopen+label%3Ahelp-wanted) is probably the best place to get started. Depending on what you're interested in, begining the conversation on one of those issues would probably be the best place to get started.

**Comment by codegaze** [comment]
Thanks @benbalter, this is what I had in my mind. Maybe this would be a great add to the contributing instructions page.
