### ISSUE TITLE
Scroll doesn't work on posts list

### ISSUE THREAD

**Issue by yoksel** [jekyll/jekyll-admin#213]
Describe in one or two sentences why you're opening this issue:
### Tell us a bit about yourself
- Version of JekyllAdmin I'm using: 0.1.0
- Version of Jekyll I'm using: 3.2.1
- Operating System: OS X
- Browser: Chrome
### Steps to reproduce
1. Open the list of posts: http://localhost:4000/admin/collections/posts
2. Try to scroll down to see more posts
### Expected

I'm expecting to see more posts
### Actual

Nothing happens, I can't scroll to older posts. For pages it works the same way.

**Comment by mertkahyaoglu** [comment]
Thanks @yoksel for reporting.

But I can't reproduce this and I believe @benbalter tested Jekyll Admin on [his personal website ](http://ben.balter.com/) which has lots of posts. Are you sure this is 100% related with Jekyll Admin? Anything on your computer or browser might be causing the problem ? Have you tested this with another machine or browser ?

**Comment by yoksel** [comment]
Sorry, I'm late : )
I updated Jekyll and JekyllAdmin, and the problem doesn't reproduce now.

**Comment by mertkahyaoglu** [comment]
Glad to hear that 👍
