### ISSUE TITLE
Update jekyll dependency to 3.2.x

### ISSUE THREAD

**Issue by virtuald** [jekyll/jekyll-admin#218]
With the specific version of gem (2.4.5) and bundler (1.7.6), adding "github-pages" and "jekyll-admin" to the same Gemfile results in the following error for whatever reason:

```
Bundler could not find compatible versions for gem "liquid":
  In Gemfile:
    github-pages (>= 0) ruby depends on
      liquid (= 2.5.1) ruby

    jekyll-admin (>= 0) ruby depends on
      jekyll (~> 3.1) ruby depends on
        liquid (3.0.0)
```

It appears the latest github-pages depends on 3.2.1, whereas jekyll-admin depends on ~3.1. Perhaps the dependency should be on 3.x, not 3.1.x... or something a bit more broad than it is now?

**Comment by benbalter** [comment]
`~3.1` should match both 3.1.x and 3.2.x. I believe the command `bundle update` should resolve your problem.

**Comment by virtuald** [comment]
Hm, I'm not a ruby users, so after misreading the gem documentation several times it appears you're right.

This is from an [empty install on travis-ci](https://travis-ci.org/firstwiki/wiki/builds/157372125)... though, it didn't break for me when I had newer versions of gem/bundler installed, so maybe it's a bug in those specific versions of gem/bundler? I'll have to look into it later I guess.
