### ISSUE TITLE
Auth configuration to access the admin area

### ISSUE THREAD

**Issue by JoseCage** [jekyll/jekyll-admin#222]
recently installed Jekyll-admin on my machine and everything worked good. However I noticed by the way / admin is accessible without restriction and so I wonder if the Jekyll-admin itself comes with some configuration to "user and password" or if it will be a feature for future versions ..

Thank you..

**Comment by benbalter** [comment]
@JoseCage can you explain a bit why you think you need a password to access the admin area? Jekyll Admin currently only runs on your local machine, and thus only you should have access.

**Comment by JoseCage** [comment]
Oops.. @benbalter. I did not know just swirled in the local environment. If thought can also be used in production so suggestion for authentication.
In this case, there is reason to use password ..
  Thanks again.
