### ISSUE TITLE
Main text field not recognised by in-browser spellcheckers

### ISSUE THREAD

**Issue by MPybus** [jekyll/jekyll-admin#232]
### Description:

When using an in-browser spellchecker, the main text field used for a page isn't recognised and therefore not checked.

Metadata and title fields seem fine.
### Tell us a bit about yourself:
- Version of JekyllAdmin I'm using: 0.1.1
- Version of Jekyll I'm using : 3.2.1
- Operating System <e.g. OS X, Windows>: Windows 7
- Browser <e.g, Safari, Chrome>: Firefox and Vivaldi
### Steps to reproduce:

Enable/install a spellchecker, create page, write garbage in the main text field.
### I expected the following:

The garbage would be highlighted as such.
### But got the following, instead:

The spellchecker didn't highlight anything.

**Comment by mertkahyaoglu** [comment]
Thanks @MPybus, we will look into this 👍

**Comment by OmarSquircleArt** [comment]
I am still having this issue in Jekyll-Admin-v 0.5.1. Should it be enabled somewhere in jekyll admin?

**Comment by mertkahyaoglu** [comment]
We disabled spellchecker via #311
