### ISSUE TITLE
Separate frontend messages into a file

### ISSUE THREAD

**Issue by mertkahyaoglu** [jekyll/jekyll-admin#241]
Currently some messages like the followings;

* `Are you sure that you want to delete FILENAME ?`
* `No data files found.`
* `Are you sure that you want to delete FILENAME ?`

are hardcoded into components (e.g. [here](https://github.com/jekyll/jekyll-admin/blob/master/src/containers/views/DocumentEdit.js#L61)). When we want to change the `delete message`, for example, we have to make changes to all of files that contains it. It would be nice to separate all messages into a file like `messages.js` so we can make changes to only that file when we want.

In addition, this would help us implement #99 easily in the future.

**Comment by benbalter** [comment]
> In addition, this would help us implement #99 easily in the future.

✨

**Comment by mertkahyaoglu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Separate frontend messages into a file](https://trello.com/c/xuhB8vIA/1-separate-frontend-messages-into-a-file)

**Comment by ashmaroli** [comment]
```
Card not found.

This card may be on a private board. You may be able to view it by logging in.
```

**Comment by mertkahyaoglu** [comment]
Wow. Wasn't expecting this 😬  Looks like Trello sends comments to Github automagically. @ashmaroli I just made the board public though in case you want to look at it.
