### ISSUE TITLE
not available with browser-sync + gulp

### ISSUE THREAD

**Issue by wangsongiam** [jekyll/jekyll-admin#243]
### Description:

I am using Gulp and BrowserSync for autoloading changes. 
<img width="1440" alt="screen shot 2016-11-11 at 12 28 10 pm" src="https://cloud.githubusercontent.com/assets/19645990/20224025/5f09262c-a80a-11e6-86d7-97edac52c55a.png">

but When I check `localhost:4000/admin`, it gives me `Cannot GET /admin`, 
<img width="311" alt="screen shot 2016-11-11 at 12 22 51 pm" src="https://cloud.githubusercontent.com/assets/19645990/20223921/ce158b2e-a809-11e6-8bff-de207abef739.png">

while everything else is fine.
<img width="516" alt="screen shot 2016-11-11 at 12 22 35 pm" src="https://cloud.githubusercontent.com/assets/19645990/20223917/c501f55e-a809-11e6-8a6c-eb9e50ccafab.png">

Then I tried just exec `bundle exec jekyll serve` without `gulp`, 
`localhost:4000/admin` worked again, so I assume the problem should occured with gulp or browser sync, this is my [gulpfile](https://github.com/wangsongiam/jekyll-starter/blob/master/gulpfile.js)

### Tell us a bit about yourself:
* Version of JekyllAdmin I'm using <HINT: use `bundle show` to check>:
❯ bundle show
Gems included by the bundle:
  * activesupport (4.2.7)
  * addressable (2.4.0)
  * backports (3.6.8)
  * bundler (1.13.6)
  * coffee-script (2.4.1)
  * coffee-script-source (1.10.0)
  * colorator (1.1.0)
  * ethon (0.9.1)
  * execjs (2.7.0)
  * faraday (0.9.2)
  * ffi (1.9.14)
  * forwardable-extended (2.6.0)
  * gemoji (2.1.0)
  * github-pages (102)
  * github-pages-health-check (1.2.0)
  * html-pipeline (2.4.2)
  * i18n (0.7.0)
  * jekyll (3.3.0)
  * jekyll-admin (0.1.1)
  * jekyll-coffeescript (1.0.1)
  * jekyll-feed (0.7.2)
  * jekyll-gist (1.4.0)
  * jekyll-github-metadata (2.2.0)
  * jekyll-mentions (1.2.0)
  * jekyll-paginate (1.1.0)
  * jekyll-redirect-from (0.11.0)
  * jekyll-sass-converter (1.3.0)
  * jekyll-seo-tag (2.0.0)
  * jekyll-sitemap (0.11.0)
  * jekyll-swiss (0.4.0)
  * jekyll-watch (1.5.0)
  * jemoji (0.7.0)
  * json (1.8.3)
  * kramdown (1.11.1)
  * liquid (3.0.6)
  * listen (3.0.6)
  * mercenary (0.3.6)
  * mini_portile2 (2.1.0)
  * minima (2.0.0)
  * minitest (5.9.1)
  * multi_json (1.12.1)
  * multipart-post (2.0.0)
  * net-dns (0.8.0)
  * nokogiri (1.6.8.1)
  * octokit (4.4.1)
  * pathutil (0.14.0)
  * public_suffix (1.5.3)
  * rack (1.6.4)
  * rack-protection (1.5.3)
  * rack-test (0.6.3)
  * rb-fsevent (0.9.8)
  * rb-inotify (0.9.7)
  * rouge (1.11.1)
  * safe_yaml (1.0.4)
  * sass (3.4.22)
  * sawyer (0.7.0)
  * sinatra (1.4.7)
  * sinatra-contrib (1.4.7)
  * terminal-table (1.7.3)
  * thread_safe (0.3.5)
  * tilt (2.0.5)
  * typhoeus (0.8.0)
  * tzinfo (1.2.2)
  * unicode-display_width (1.1.1)

* Version of Jekyll I'm using <HINT: use `bundle show` to check>:
* Operating System <e.g. OS X, Windows>:
OS X
* Browser <e.g, Safari, Chrome>:
canary chrome

**Comment by mertkahyaoglu** [comment]
The reason is your gulp file is not calling `bundle exec jekyll serve` which starts the ruby development server where the admin panel is available. The server that browser-sync starts do not have Jekyll Admin. It just serves the `_site` folder.
 
You can try [jekyll-livereload](https://github.com/RobertDeRose/jekyll-livereload) instead.

**Comment by wangsongiam** [comment]
Thanks for your quick reply, but I should have called `bundle exec jekyll serve`, you can check my [gulp file](https://github.com/wangsongiam/jekyll-starter/blob/master/gulpfile.js), I used `gulp-shell` plugin for auto shell command in line 6 :
`gulp.task('build', shell.task(['bundle exec jekyll build --watch']));`
Also, I've tried `jekyll-livereload`, it's good but couldn't auto refresh my browser, so I really want gulp work it out.

**Comment by mertkahyaoglu** [comment]
It's actually bundle exec jekyll **build** 😬

**Comment by wangsongiam** [comment]
Opps...my bad

**Comment by mertkahyaoglu** [comment]
No problem at all 👍
