### ISSUE TITLE
Editor breaks configuration file and datafiles

### ISSUE THREAD

**Issue by ashmaroli** [jekyll/jekyll-admin#246]
### Description:

The Editor under /configuration and /datafiles breaks datafiles containing the fold character and comments`>`

### Tell us a bit about yourself:
* Version of JekyllAdmin I'm using <HINT: use `bundle show` to check>: 0.1.1
* Version of Jekyll I'm using <HINT: use `bundle show` to check>:3.3.1
* Operating System <e.g. OS X, Windows>:**_Windows 7_**
* Browser <e.g, Safari, Chrome>:Chrome

### Steps to reproduce:

- Copy `email:` and `description:` from a Jekyll site's `_config.yml`
- Add a few lines of comments to the **spec's config file**
- Run `script/server-frontend`
- Edit the **spec's config file** by pasting the content copied earlier.
- Hit Save
- Examine the **spec's `_config.yml`**
### I expected the following:

- The file content to be a valid YAML file
- The comments to not be deleted.

### But got the following, instead:

- The file to be broken after `description:`
- Existing comments deleted

### Other details:

N/A

**Comment by mertkahyaoglu** [comment]
@benbalter @parkr Is there a way the api can send the raw configuration as yaml rather than [json](https://github.com/jekyll/jekyll-admin/blob/master/lib/jekyll-admin/server/configuration.rb#L5)? This way, the front end does not have to parse it back to YAML, which will preserve comments.

**Comment by parkr** [comment]
That's a great idea! You would have to re-read the file but yeah we should be able to read the file as-is and allow it to be written again as-is. @benbalter: sound possible to you?

**Comment by ashmaroli** [comment]
fixed.

**Comment by mertkahyaoglu** [comment]
@ashmaroli How is this fixed ? 😄

**Comment by ashmaroli** [comment]
@mertkahyaoglu this issue is no longer reproducible on `master` :smiley:

**Comment by mertkahyaoglu** [comment]
Awesome then :man_dancing:
