### ISSUE TITLE
Can I change the url of view buttons ?

### ISSUE THREAD

**Issue by cegedr** [jekyll/jekyll-admin#247]
### Description:

My local jekyll is serving on one computer on the LAN. 
And I browser my site on another computer using the LAN ip of that computer, like `http://10.108.124.67:4000/admin/` .
However, the view button always direct to `http://0.0.0.0:4000/***`

### Tell us a bit about yourself:
* Version of JekyllAdmin I'm using: `jekyll-admin (0.1.1)`
* Version of Jekyll I'm using : ``jekyll (3.3.0)
* Operating System: Ubuntu 14.04
* Browser: Chrome

**Comment by mertkahyaoglu** [comment]
You can't change it. The url is coming from the api. The example payload for a page like this;

``` json
{
"some_front_matter": "default",
"foo": "bar",
"dir": "/",
"name": "page.md",
"path": "page.md",
"url": "/page.html",
"http_url": "http://localhost:4000/page.html",
"api_url": "http://localhost:4000/_api/pages/page.md"
}
``` 

The front end uses the `http_url` for view buttons.

**Comment by neonsoftware** [comment]
Hi ! I encountered this today trying to do the same thing. I would specifying a different host quite useful, as it would basically make it a CMR. 

Could this be in a issue as feature request to gather info form eventual other users that might be interested in not using only 0.0.0.0 in the future ? Just in case

I ask here before-hand. Cheers 😄
