### ISSUE TITLE
jekyll/admin or jekyll-admin?

### ISSUE THREAD

**Issue by benbalter** [jekyll/jekyll-admin#25]
[Technically, technically](http://guides.rubygems.org/name-your-gem/), in Ruby land, `jekyll/admin` would be Jekyll::Admin and `jekyll_admin` would be `JekyllAdmin`.

In Jekyll land, we have a convention of calling everything `jekyll-X` (e.g.., `jekyll-feed`). 

@parkr any strong feelings if this should be `jekyll/admin` or `jekyll-admin`?

**Comment by parkr** [comment]
@benbalter It doesn't make a big difference to me. The only piece is that if you add `jekyll-admin` to `gems` in your `_config.yml`, it will run `require "jekyll-admin"`, so it needs to be require-able from that name. I'd leave it as-is.

**Comment by nhoizey** [comment]
Well, maybe it's time to review/complete this [Jekyll style guide](http://ben.balter.com/jekyll-style-guide/plugins/#naming) and publish it in [the official doc](http://jekyllrb.com/)? ;-)

**Comment by benbalter** [comment]
Ha. Okay. So taking [my own advice](http://ben.balter.com/jekyll-style-guide/plugins/#naming), it should be `Jekyll::JekyllAdmin` so that it can be loaded and distributed as `jekyll-admin` rather than `jekyll/admin`.

**Comment by nhoizey** [comment]
So I wonder, I followed Jekyll Assets example for my [new Jekyll Cloudinary plugin](https://github.com/nhoizey/jekyll-cloudinary), which seems to be a bad idea.

I think such conventions should really be documented and explained.

**Comment by nhoizey** [comment]
@benbalter sorry, but I don't understand why you say this:
> it should be `Jekyll::JekyllAdmin` so that it can be loaded and distributed as `jekyll-admin` rather than `jekyll/admin`

My Cloudinary plugin module is `Jekyll::Cloudinary`, but it is loaded with `gem 'jekyll-cloudinary'` in my `Gemfile`, not `gem 'jekyll/cloudinary'`.

I think I'm missing something here, I'm still new to Ruby and Jekyll plugins…

**Comment by benbalter** [comment]
@nhoizey see http://guides.rubygems.org/name-your-gem/ (which is what I recently learned from).

**Comment by nhoizey** [comment]
Ok, so you recommend not following your advice in http://ben.balter.com/jekyll-style-guide/plugins/#naming ? ;-)
