### ISSUE TITLE
Encoding bug within Editor

### ISSUE THREAD

**Issue by ashmaroli** [jekyll/jekyll-admin#257]
I'm running the `server-frontend` script with latest `master` on Windows.
I have a `datafile.yml` within the fixture site's `_data` folder with valid YAML data.

one of the lines being:  
```yaml
name: Jekyll • Simple, blog-aware, static sites
```

As seen when simply opened via `/datafiles`:

![ja](https://cloud.githubusercontent.com/assets/12479464/21520258/1c575eb4-cd19-11e6-8bce-86d1710680a6.png)

As seen on first edit and save:

![ja1](https://cloud.githubusercontent.com/assets/12479464/21520277/40d0c67c-cd19-11e6-8bec-1239a717b599.png)

As seen after another edit and save:

![ja2](https://cloud.githubusercontent.com/assets/12479464/21520294/62239b56-cd19-11e6-80bf-4bcd76799641.png)

**Comment by mertkahyaoglu** [comment]
@ashmaroli This is certainly a Windows issue. I updated the packages related with Ace Editor with #260 . Could you check again with the current master?

**Comment by ashmaroli** [comment]
Could be either the OS or just the editor (ace had a bug with rendering "non-english letters" which was fixed in 0.9.1). But I couldn't install ace-0.9.1 as I didnt have the `build-tools` package installed on my system. 
So wont be able to test this.. 

Thanks.

 You may close if you're not able to reproduce this at your end.

**Comment by mertkahyaoglu** [comment]
I will try this in my Windows machine if I have time 👍

**Comment by ashmaroli** [comment]
remove-label: `pending-feedback` :smile:
