### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by editicalu** [jekyll/jekyll-admin#258]
To be able to use this admin panel on a production server, it would be a good idea to have some kind of authentication.

- [ ] Implement a file with usernames and (hashed) passwords (could and should be done inside `_config.yml`)
- [ ] Create a login form

**Comment by mertkahyaoglu** [comment]
Duplicate of #222. Currently Jekyll Admin runs locally so we don't need any authentication. We might have this in the future when Jekyll Admin can be hosted on the cloud.

**Comment by bishisht** [comment]
Any updates to having login to access admin panel?
