### ISSUE TITLE
Posts page list show "Invalid Date"

### ISSUE THREAD

**Issue by gbonline** [jekyll/jekyll-admin#270]
### Description:

In a fresh installation of jekyll and jekyll-admin at latest versions, in Posts page, it show "Invalid Date" for the listed posts

### Tell us a bit about yourself:
* Version of JekyllAdmin I'm using <HINT: use `bundle show` to check>: latest today 0.2.0
* Version of Jekyll I'm using <HINT: use `bundle show` to check>: 3.3.1
* Operating System <e.g. OS X, Windows>: ubuntu 16.04 64bit 
* Browser <e.g, Safari, Chrome>: FF 50.1.0

* Interpreter: Ruby 2.4.0 in RVM 1.28

### Steps to reproduce:

Both default post and a new post show invalid date

### Other details:

A screeshot: 
![schermata del 2017-01-12 16-46-52](https://cloud.githubusercontent.com/assets/3273873/21896825/f3c83e66-d8e7-11e6-8e3f-c72b92a1d850.png)

**Comment by mertkahyaoglu** [comment]
Thanks for reporting @gbonline . Looks like `date` is not valid on other browsers except Chrome 😞
