### ISSUE TITLE
Documents and Pages metadata contain frontmatter defaults

### ISSUE THREAD

**Issue by benbalter** [jekyll/jekyll-admin#30]
See https://github.com/jekyll/jekyll-admin/pull/28#issuecomment-231075285.

I'd like to propose that we *remove* front matter defaults, even if explicitly present in the front matter. It's a compromise that isn't too difficult to implement technically, is better than the alternative, and has the added affect of removing duplicative front matter data.

**Comment by parkr** [comment]
> has the added affect of removing duplicative front matter data.

How so? Defaults are defaults – if you already have a `layout`, for example, then the default value won't be shown. It'd be useful to see all the metadata that the document has, including defaults. I think it shouldn't be editable, but it should be shown.

**Comment by benbalter** [comment]
>  I think it shouldn't be editable, but it should be shown.

So we should parse the YAML from the document directly? How do we cleanly get that, and the other `to_liquid`-injected values (e.g., date), without getting the defaults?
