### ISSUE TITLE
Post Preview incorrectly parses URL

### ISSUE THREAD

**Issue by JohannesMP** [jekyll/jekyll-admin#306]
### Description:

The following:
```md
[foo](https://en.wikipedia.org/wiki/Pointer_(computer_programming)) bar
```
Is incorrectly rendered:
![](https://i.imgur.com/E4AMheZ.png)

When the actual live view (or github's own markdown renderer) display it correctly:
- [foo](https://en.wikipedia.org/wiki/Pointer_(computer_programming)) bar

### Tell us a bit about yourself:
- ruby v2.3.3p222
- jekyll-admin v0.3.0
- jekyll v3.3.1
- Windows 10
- Chrome v56.0.2924.87 (64-bit)

### Other details:

Screencapture:
![](http://i.imgur.com/i543aDF.gif)

**Comment by mertkahyaoglu** [comment]
Thanks @JohannesMP 👍 . Going to report this to [simplemde](https://github.com/NextStepWebs/simplemde-markdown-editor) repo.

**Comment by mertkahyaoglu** [comment]
The problem is [marked](https://github.com/chjj/marked) package not parsing the links properly. Sadly nothing we can do. Alternative usage is described [here].(https://github.com/NextStepWebs/simplemde-markdown-editor/issues/528).
