### ISSUE TITLE
Disable spellchecker

### ISSUE THREAD

**Issue by jungornti** [jekyll/jekyll-admin#311]
### Description:
Spellchecker is enabled by default and do not work for Russian (and possibly other) language. It marks every word as incorrect.

### Tell us a bit about yourself:
JekyllAdmin version is 0.4.0
Jekyll version is 3.4.0
OS: Linux Mint
Browser: Google Chrome 56.0.2924.87 (64-bit)

### Steps to reproduce:
Install jekyll admin, create new post and enter any phrase in Russian, "Привет, мир!", for example.

### The problem:
Every single Russian word is marked with light−red background.

### Other details:
[Picture, describing the problem](https://cloclo27.datacloudmail.ru/weblink/view/2ahC/c4EBgV7EW?etag=9369E58DE27E77C726CB1EEFAFB5081A3C0B34FB&key=a9efd28c50eb852e08806b29f40996ff28a637e8)

**Comment by mertkahyaoglu** [comment]
Hmm. Let's disable it until `spellchecker` package supports multilanguage.

**Comment by jungornti** [comment]
Thank you very much!
