### ISSUE TITLE
Editing post created before jekyll admin.

### ISSUE THREAD

**Issue by OmarSquircleArt** [jekyll/jekyll-admin#316]
### Description:
Hello

I just started using jekyll admin and I am having a bit of trouble in using it.

First, When I try to edit existing posts which I wrote not using admin, it return an error related to the file name. Is this my fault or is it a some kind of a bug?
![Error](https://cloud.githubusercontent.com/assets/25300994/23589967/1f5c6482-01e0-11e7-97c7-4ef960c35f46.png)

***
Another thing, when I create a new post or edit it, it return an error:

![error2](https://cloud.githubusercontent.com/assets/25300994/23589971/52e38c22-01e0-11e7-9f4d-fcb0e17d1ef1.png)

Is this normal?

### Tell us a bit about yourself:
Version: 0.4.0
Jekyll Version: 3.3.1
Arch Linux
Chrome

### Steps to reproduce:
Edit and try to save a file that was created without jekyll admin.

**Comment by mertkahyaoglu** [comment]
The first issue is because it expects 2 digits for the month section. I believe second issue is related with #289 . Is that happening all the time or sometimes?

**Comment by OmarSquircleArt** [comment]
First problem solved, thanks.
Second problem happens often, however, things work perfectly in spite of the error, I mean that when I press save for instance, it give the error but it saves fine.

**Comment by mertkahyaoglu** [comment]
Yeah, that's the issue. We are trying to fix it soon. Thanks for getting in touch 👍
