### ISSUE TITLE
Strip spaces after metadata field label

### ISSUE THREAD

**Issue by ecupaio** [jekyll/jekyll-admin#338]
### Description:
If a user adds a space at the end of a metadata field label, it turns the front matter into a string and causes it not to work. I release they can just remove the space in the admin, but my users are humans that make mistakes sometimes and don't know the intricacies of jekyll admin like I do. #

[Screenshot of metadata field with space at end](http://i.imgur.com/o9wxWR0.png) leads to this in the front matter: `'status ': live`

### Tell us a bit about yourself:
Jekyll Admin v0.4.1

### Steps to reproduce:

1. Create a new document
2. Add a new metadata field
3. Enter a label for the new field, then add a space at the end
4. Enter content for the new field
5. Select Save
6. Look at the new md document in your repo

You can also try to load your content with liquid: ex {{ page.new_field }}

### I expected the following:
I would like for Jekyll Admin to remove extra spaces at the end/beginning if they exist. 

### But got the following, instead:
I get a unusable front matter item that messes up my whole operation

**Comment by jrsales** [comment]
Am i the only one not being able to type anything with a space in it?
I can copy-paste whole sentences, but if i type the same sentence my spaces are automatically removed as soon as i type them.

**Comment by ashmaroli** [comment]
@jrsales Thanks for pointing that bug out. Will send a patch in the near future. Till then, start multi-worded values with a pair of quotes and type within the quotes.. :wink:

**Comment by ashmaroli** [comment]
Opened a PR at #365
