### ISSUE TITLE
Path /admin in gh-pages

### ISSUE THREAD

**Issue by gkal19** [jekyll/jekyll-admin#341]
### Description:
I just installed the plugin on my blog that is stored in a repository in Github Pages.
The problem is when I will want to access the `/admin` page, I end up having an error and says it is not localized. Being that I installed it correctly.

I hope you have understood.

* Version of JekyllAdmin I'm using 0.4.1
* Version of Jekyll I'm using 3.4.3
* Operating System: Windows (unfortunately)
* Browser : Chrome

![Screenshot of the problem](http://i.imgur.com/2bC1PDh.png)

**Comment by ashmaroli** [comment]
`jekyll-admin` only works locally

**Comment by gkal19** [comment]
Now I understand! Thank you

**Comment by ashmaroli** [comment]
You may close this ticket then
