### ISSUE TITLE
Front Matter Date Time Selector does not respect AM/PM rules

### ISSUE THREAD

**Issue by ecupaio** [jekyll/jekyll-admin#346]
Version 0.3.0

When I create a date front matter field and use the selector for the time, the PM time does not get converted to the 24 hr format in the raw markdown file. 

If I enter 5:30 PM, the time should be 17:30:00 in the raw markdown file, but it appears as 05:30:00.

**Comment by altcointrading** [comment]
@ecupaio Not a solution but a possible workaround for your problem could be using a plugin called jekyll-last-modified-at that adds the full datetime field programatically.

**Comment by ecupaio** [comment]
@altcointrading :/ not what I'm going for. I'm using the date slot for an event calendar. I just input the time on the markdown file. Nonetheless, when a user selects 8:00 pm the time should be 20:00. That's just bad UI design

**Comment by mertkahyaoglu** [comment]
You're right. This is bad. I don't know how we missed it 😞 . The front-end relies on `react-widgets` package for the datepicker. Let me see if I can replace/fix it. Thanks for the issue @ecupaio 👍
