### ISSUE TITLE
Missing "babel-register" Module

### ISSUE THREAD

**Issue by gDelgado14** [jekyll/jekyll-admin#352]
### Description:
When running `script/build`, I get an error specifying that the `babel-register` module cannot be found. 

babel-register is not within the package.json

### Tell us a bit about yourself:
* jekyll-admin (0.4.1)
* jekyll (3.4.3)
* OS X

### Steps to reproduce:
Run `script/build` immediately after running `script/bootstrap`

### I expected the following:
Expected the site to be built without errors

### But got the following, instead:
Error: Cannot find module 'babel-register'

**Comment by mertkahyaoglu** [comment]
`babel-register` has been moved under `babel-core`. That's why it's not within `package.json`. I'm not reproducing this issue. Travis is not giving any error as well.

Which version of Node are you using?

**Comment by gDelgado14** [comment]
Fixed. I was initially running with node v4.5.0. Switched to v6.4.0 and there were no problems. 

However, I don't recall seeing any mention of node version requirements. Maybe this could be added for clarity?

**Comment by mertkahyaoglu** [comment]
You are right 👍 

 I added that via db0874a . Thanks for reporting @gDelgado14
