### ISSUE TITLE
ability to hide unused features

### ISSUE THREAD

**Issue by bcullman** [jekyll/jekyll-admin#353]
### Description:
Is there some sort of config file i can use to enable/disable Jekyll Admin features?

Not sure I am ever going to use Jekyll `posts`. Since I have none, clicking it gives me an error. Would like a way to hide the item in the navigation. 

Might want to hide the `configuration` item too - not sure what is used for.

### Tell us a bit about yourself:
* Version of JekyllAdmin I'm using <HINT: use `bundle show` to check>: 0.4.1
* Version of Jekyll I'm using <HINT: use `bundle show` to check>: 3.4.3
* Version of NodeJS I'm using <HINT: use `node -v` to check>: 7.9.0
* Operating System <e.g. OS X, Windows>: OSX
* Browser <e.g, Safari, Chrome>: Various

**Comment by ashmaroli** [comment]
Hi @bcullman there isn't a config setting for enabling/disabling Admin features as of now.
We should be able to add a patch that'd disable links on the `sidebar` if the associated array / collection is empty... or even hide that link altogether.

The `Configuration` item is for editing your `_config.yml` and in a future version, display/edit the currently used config file.

**Comment by mertkahyaoglu** [comment]
@bcullman What kind of error are you getting ? It should say "No posts found" if there are none.

**Comment by bcullman** [comment]
Yep, it does say: "No posts found".

My point is that I am setting this up for other less technical people. I would prefer to hide the features we don't use - we don't have posts, nor will we ever have them.

I don't _think_ you should patch to disable if the array is empty - there are likely others consumers of this repo that are perfectly happy showing their users post's are currently empty, and that they are free to add them.

Honestly, if you just exposed a CSS file for us to alter, that would be plenty - we could "hide" this feature, plus, bonus, we could brand the interface

**Comment by mertkahyaoglu** [comment]
> I don't think you should patch to disable if the array is empty

I agree. This should be optional. Maybe reading hidden links from config file could work.
