### ISSUE TITLE
Strategy for jekyll-admin in production

### ISSUE THREAD

**Issue by cameronmcefee** [jekyll/jekyll-admin#386]
Hello!

I'm digging into jekyll-admin and it seems like a really cool utility. I don't see mentioned in the docs whether it appears in production, but my testing of setting `JEKYLL_ENV=production` seems to indicate it does. What's the suggested strategy for protecting it, and how does it work?

**Comment by ashmaroli** [comment]
Hello @cameronmcefee, currently `jekyll-admin` runs only on the local server (`http://localhost:4000/admin`) regardless of the `JEKYLL_ENV` It won't run on GitHub Pages or elsewhere like Heroku.
Simply add the plugin to your `Gemfile`/`_config.yml`, start up Jekyll server and head to `/admin/`

**Comment by cameronmcefee** [comment]
Oh, great. Thanks for clarifying!

**Comment by raja-anbazhagan** [comment]
@ashmaroli Just to confirm, If I run this on my private hosting with `jekyll serve` I would be exposing the admin UI right? Any plan on providing authentication mechanism for this? perhaps an `[.htaccess]`?

**Comment by ashmaroli** [comment]
> I would be exposing the admin UI right?

Jekyll Admin piggybacks on Jekyll's built-in `WEBrick` server to mount the API endpoints. So in theory, the Apache or NGINX adapters on your private hosting may not mount the API url at all.. (but I could be very wrong..)
Either ways, currently, the lead maintainer here is focusing on revamping the Frontend component of the interface.
That said, feel free to submit a PR that would add basic authentication to the interface

**Comment by Lelith** [comment]
i m also interested in that topic and have been thinking about protecting it with the help of auth0

**Comment by iboware** [comment]
Is there any plan or possibility making jekyll-admin compatible with nginx?
