### ISSUE TITLE
Feature request: Save post without scrolling to top of page

### ISSUE THREAD

**Issue by mtlynch** [jekyll/jekyll-admin#388]
### Description:

It would be nice if the "Save" button scrolled down the page as the user scrolled down

![image](https://cloud.githubusercontent.com/assets/7783288/26284698/81cd0a48-3e0f-11e7-816c-8f6dd8b94766.png)

### Tell us a bit about yourself:
* Version of JekyllAdmin I'm using: 0.5.0
* Version of Jekyll I'm using: 3.4.3
* Version of NodeJS I'm using: N/A
* Operating System: Ubuntu 16.04 server
* Browser: Chrome

### Steps to reproduce:

1. Write a long blog post
1. Scroll down to the bottom of the post
1. Attempt to save the page

### I expected the following:

I can either save with a hotkey or the "Save" button scrolls with me so it is always visible on the screen.

### But got the following, instead:

I need to scroll all the way back up to the top of the page every time I want to save.

**Comment by mertkahyaoglu** [comment]
I have a better solution. How about `ctrl+s` ? 😄 
We support saving via keyboard shortcut with v0.5.0 release.

**Comment by ashmaroli** [comment]
I think having the `side-buttons` scroll with the page would be a nice addition.. the entire strip of screen space under the side-buttons remain bare anyways..
The additional use-case is that a user need not scroll up to make sure that the `save` action has been dispatched as intended..

**Comment by mertkahyaoglu** [comment]
Agreed 👍  As a whole, making side-buttons fixed would me more user-friendly.

Before applying any css to it, it would be a good practise to make a wrapper component for those buttons and make changes to a single place.

**Comment by mtlynch** [comment]
>We support saving via keyboard shortcut with v0.5.0 release.

Oh, that's great! Is there a list of keyboard shortcuts available?

This is a new thing, right? I think I tried that a few months ago and Chrome thought I was trying to save a local copy of the web page.

**Comment by ashmaroli** [comment]
> Is there a list of keyboard shortcuts available?

Currently only one has been defined and tested: the combo for save..
