### ISSUE TITLE
When `GET /static_files/:path` is called on a directory, it should return that directory's static files

### ISSUE THREAD

**Issue by benbalter** [jekyll/jekyll-admin#39]
Note: that this should be the directory's *static files*, as seen by Jekyll, not all files in the directory.

**Comment by tekknolagi** [comment]
Does this currently work for a directory's files anyway? Right now I cannot access `/static_files/mystaticdir/file.txt`. Is this expected?

**Comment by benbalter** [comment]
> Does this currently work for a directory's files anyway?

Good catch. You are correct, I tested locally, and confirmed it currently only works for top-level files. If you interested in tackling both in once pass, if they're closely related, awesome.  I suspect we'll need to pull the `static_file` name as a splat, rather than a named parameter (to allow for `/`s in the id).
