### ISSUE TITLE
Online CMS Administrator

### ISSUE THREAD

**Issue by klopango** [jekyll/jekyll-admin#417]
### Description:

I was just watching the facemash scene from The Social Network, it seem's that he is updating his blog post in an online CMS, I was wondering if I could do that with jekyll.

I usually use Jekyll-Admin locally, but I wonder if I could use it online. Not only in local.

### Tell us a bit about yourself:
* Version of JekyllAdmin I'm using : <Latest?>
* Version of Jekyll I'm using : <3.4.3>
* Version of NodeJS I'm using : <v6.10.2>
* Operating System : OS X
* Browser : Chrome

**Comment by klopango** [comment]
Still waiting for responses.

**Comment by mertkahyaoglu** [comment]
Unfortunately you can't for now. Related with #75 , #414 .
