### ISSUE TITLE
Add config options to docs

### ISSUE THREAD

**Issue by JohannesMP** [jekyll/jekyll-admin#436]
While writing #435 I noticed that, while Jekyll admin has [dedicated documentation](https://jekyll.github.io/jekyll-admin/), it does not contain a page for which config settings can be used in `_config.yml`.

[README.md](https://github.com/jekyll/jekyll-admin/blob/master/README.md) provides a sample config for hiding links, but it is not clear if this is the complete set of config options currently available (since a repo's readme often only show a brief overview, reserving the complete extent of features for the docs).

Even if `hidden_links` is currently the only option for jekyll admin that you can use in `_config.yml`, having a dedicated config page in the docs would make it easier for users to verify.

**Comment by mertkahyaoglu** [comment]
Makes sense 👍 Could you open a PR for this?

**Comment by JohannesMP** [comment]
Done. Basically just contains what is on in Readme.md right now.
