### ISSUE TITLE
Check for invalid YAML

### ISSUE THREAD

**Issue by mertkahyaoglu** [jekyll/jekyll-admin#45]
If users try to update a YAML file with invalid content, it gives parsing error and nothing is shown to users. Instead, an error message should be shown.

**Comment by DirtyF** [comment]
This issue seems to have been resolved, notifications are displaying parse errors when YAML is not valid on save.

**Comment by mertkahyaoglu** [comment]
Yes, I forgot to close this. Thanks for reminding @DirtyF 👍
