### ISSUE TITLE
Feature Request : Ghost Style Live View Pane 

### ISSUE THREAD

**Issue by jatindhankhar** [jekyll/jekyll-admin#453]
### Tell us a bit about yourself:
* Version of JekyllAdmin I'm using <HINT: use `bundle show` to check>: 0.8.0
* Version of Jekyll I'm using <HINT: use `bundle show` to check>:  (3.4.3)
* Version of NodeJS I'm using <HINT: use `node -v` to check>: None
* Operating System <e.g. OS X, Windows>: Arch Linux
* Browser <e.g, Safari, Chrome>: Chrome

### Other details:

Jekyll admin is great for writing posts but there is one feature that I believe will be helpful. 
It would be great if we could have Ghost Style Side by Side Live View of the post in writing, so as to make quick changes without needing to go a tab or refreshing.
Sample Image - [Credit](http://www.growingwiththeweb.com/2016/01/migrating-a-blog-from-jekyll-to-ghost.html) 
<img src="http://www.growingwiththeweb.com/images/2016/01/18/editor.png">
For starters a simple iframe can be embedded ? (Which will be simple since View button for now opens a new tab) or having a separate pane for preview (which is part of standard edtior UI and it needs to clicked to preview markdown)  ?

Thank you.

**Comment by mertkahyaoglu** [comment]
Hi @jatindhankhar. We already have this feature. You need to press this button in the editor;

![button](https://user-images.githubusercontent.com/7414026/37245253-5d53f11c-24a6-11e8-8339-01e362e63a99.png)

**Comment by jatindhankhar** [comment]
Thank you, got it.
