### ISSUE TITLE
How to show post image on home page

### ISSUE THREAD

**Issue by jovil** [jekyll/jekyll-admin#457]
### Description:
How can I show post images on the front page? 

### I expected the following:
Display post images on home page.

### But got the following, instead:
Each post only displays date & title.

**Comment by mertkahyaoglu** [comment]
Hi @jovil . I don't think this is an issue with Jekyll Admin but I will try to answer your question.
You can add `image` front matter variable set to the path of an image you want to show for your post like this;
```
---
layout: post
title:  "Your Blog Title Here"
featured_img: /img/posts/your-post-title/featured.png
---
```
and then use that variable in your front page loop to show images;

````
{% for post in site.posts %}
  <img src="{% post.feature_img %}" />
{% endfor %}
```

**Comment by reda-jaifar** [comment]
in which file should i put this snippet

{% for post in site.posts %}
  <img src="{% post.feature_img %}" />
{% endfor %}

thanks

**Comment by ashmaroli** [comment]
@reda-jaifar In whichever page you want the list of images to render..
(Most likely `index.markdown` or `index.html`)..
