### ISSUE TITLE
Can't Access from Host Windows Machine

### ISSUE THREAD

**Issue by umutdogan** [jekyll/jekyll-admin#469]
Hi, 

This project looks promising but I've one suggestion: I'm doing these development activities on my local Centos7 VM. And after deploying jekyll-admin, I was able to access it through http://localhost:4000/admin inside my VM. But I tried disabling firewall, selinux etc. and it does not allow me to access the admin page through my host Windows server using its ip eg. 192.168.1.102:4000/admin. I read this is a limitation for the security. Is that correct and is there a workaround for cases similar to mine?

Thanks,
Umut

**Comment by tomer** [comment]
>  I read this is a limitation for the security. Is that correct and is there a workaround for cases similar to mine?
Have you tried to launch Jekyll with `-H 192.168.1.102`? Please note that this is not Jekyll-Admin specific issue if you couldn't access different pages on the server as well.

**Comment by mertkahyaoglu** [comment]
I agree with @tomer 👍

**Comment by umutdogan** [comment]
Verified "bundle exec jekyll serve -H 192.168.1.102" works as expected.  Thanks!

**Comment by tomer** [comment]
@umutdogan Please note that using your IP as parameter to `jekyll serve` require you to know in advance your IP address (which may change sometimes etc.). You can, however bind the server to [`0.0.0.0`](https://en.wikipedia.org/wiki/0.0.0.0) (INADDR_ANY) which will set the server to listen on any available network interface.
