### ISSUE TITLE
Development Installation Not Working on Ubuntu 15.10 & 16.04

### ISSUE THREAD

**Issue by jakebruemmer** [jekyll/jekyll-admin#48]
I was unable to run the scripts described on the [development docs](https://github.com/jekyll/jekyll-admin/blob/master/docs/development.md) page. Here's an image of the errors that I got:

![install_error](https://cloud.githubusercontent.com/assets/7538587/16913803/cab17cb6-4cb2-11e6-9018-2ffd68b6058c.png)

I also needed to add `sudo` in front of `npm install -g json-server` in `script/bootstrap` because the symlink that `json-server` was trying to create had a permissions issue. This might not happen on a mac? I'm not sure. 

[Gist of my npm-debug.log output](https://gist.github.com/jakebruemmer/53c73a8cabecc4869218da9cbdb48e96).

**Comment by mertkahyaoglu** [comment]
Thanks for the issue ❤️ 

> I also needed to add sudo in front of npm install -g json-server in script/bootstrap

We won't need `json-server` once #42 gets merged. It was just for development while our API was not ready.

Other errors that you provided might be related with Linux. We are going to test the project in different operating systems once it is completed. For now, it is still under development but thanks for pointing it out. Jekyll Admin should be compatible with all operating systems ✨ 

/cc @benbalter

**Comment by jakebruemmer** [comment]
FWIW, I was able to get further along in the test script `script/cibuild` after manually installing `codemirror` and `marked` with an `npm install`. I'm guessing that these two packages weren't included in `package.json` at `lib/jekyll/admin/public` because everyone developing this package already had them installed globally on their system. Still not able to run the test frontend though.

**Comment by mertkahyaoglu** [comment]
I understand now. Front-end uses the fork of [SimpleMDE](https://github.com/NextStepWebs/simplemde-markdown-editor) library because `spell checking` was a bit problematic and I decided to leave that out. Here is the [fork](https://github.com/mertkahyaoglu/sme) which is mine. 😁  If you look at the dependencies, they are the ones cause you the problem. I have no idea how they are not installed with `npm install`.

It looks like current version of the SimpleMDE solved this issue. We can start to use the original module again. Thanks @jakebruemmer 👍

**Comment by jakebruemmer** [comment]
Yeah, looks like those dependencies are causing the installation issue. I'm now getting a separate issue with a `Bus error (core dumped)` which is surprising because my system isn't getting anywhere close to my available memory when trying to run through the tests.

**Comment by mertkahyaoglu** [comment]
Can you find out which test exactly causing this error? Looks like it is trying to access a memory area which it is not supposed to.

**Comment by jakebruemmer** [comment]
Seems to be from `babel-node tools/srcServer.js` which is run from the `open:src` script in package.json. Here's an image of the output that I get:

![core_dump_error](https://cloud.githubusercontent.com/assets/7538587/16932250/e8bf2b38-4d0a-11e6-8f20-b0b10332c76d.png)

The server core dumps right after it tries to open up a browser to show the running server's root page. It's very likely that this is an issue with Ubuntu.

**Comment by mertkahyaoglu** [comment]
Looks like watching files is causing the bus error. Yeah, it might be related with Ubuntu. Maybe upgrading it solves this problem?

**Comment by jakebruemmer** [comment]
I just upgrade to 16.04 and it happened again when I ran `npm start` in `lib/jekyll/admin/public` :(.

**Comment by jakebruemmer** [comment]
Great news! I got it working after updating my node and ruby versions! I also had a bunch of gems that I had built with `bundle` when I was using `rvm` so I was getting errors with my shebangs in all of my `~/.gem/bin` binaries. Anyways, it's up and running now with node version `v6.2.2` and ruby `2.3.1`. 

You can close out this issue and direct others installing on ubuntu to me.

Thanks

**Comment by mertkahyaoglu** [comment]
@benbalter Is it possible to update travis to test against different versions of NodeJS/Ruby?
