### ISSUE TITLE
The data files are getting deleted when editing in Raw Editor

### ISSUE THREAD

**Issue by vinaynellagi** [jekyll/jekyll-admin#482]
We are using Data files in our project and when we try to edit the Data files in Raw Editor mode from the Jekyll-admin, the error shows up stating could not update file and then when we go back to Data files list the file is deleted.

When we inspect, in the console we get an error - fetch.js:53 PUT http://localhost:4000/_api/data/foobar.yml 500 (Internal Server Error)

The versions that we are using are - 
jekyll - 3.8.4
jekyll-admin - 0.8.1
OS Ubuntu 16.04 and Also on macOS 10.13.5
Browser - Chrome - 64.0.32 and 71.0.3578.98 respectively.

Any help on this matter will be highly appriciated.

**Comment by vinaynellagi** [comment]
Or is it possible to disable Raw Editor mode and show only the GUI mode ?

**Comment by parv16** [comment]
The same issue is happening. Data files getting deleted when editing in raw mode and it says unable to edit file as a error message.  
Also its creating modified file with name undefined. 
Possibly it is unable to get path of editing file.

However, yaml or json files are editing perfectly in gui mode.

I have csv files in data files which is neither editable by gui editor.

Please look into this issue...

**Comment by lexoyo** [comment]
Hello,
I think I'll give it a shot but I'm new to jekyll admin so... I'll let you know

**Comment by lexoyo** [comment]
Took me 2 hours to figure out what happens and fix it
I like this project, and I see several things I could do to improve the UX

**Comment by parv16** [comment]
@lexoyo, What was happening while editing data files in raw_mode?

**Comment by lexoyo** [comment]
Undefined was passed as the new file name to the back

**Comment by lexoyo** [comment]
Did you see my comments on the PR?
#486

**Comment by parv16** [comment]
Seen. Got the problem. I have Intuition that problem is something like that only
Thanks a lot for your effort..

**Comment by vinaynellagi** [comment]
Awersome.. We had disabled that button for sometime.. Will try the suggest fix... Thank you for putting in the effort.

**Comment by lexoyo** [comment]
I wanted to get familiar with the project and do something useful

**Comment by mertkahyaoglu** [comment]
@lexoyo Thanks for taking care of this. It's good to see contributors like you.
Unfortunately I can't maintain the project for some time. Hope I'll be back soon.

**Comment by lexoyo** [comment]
Oh ok I hope that it is nothing serious and bad. Thank you for starting this

Feel free to give me the rights to merge if you think nobody else can do code reviews (i would prefer that someone who knows the projects do it but it is better me than nobody)
