### ISSUE TITLE
Adding this to my site behind username and password?

### ISSUE THREAD

**Issue by GiacomoLaw** [jekyll/jekyll-admin#483]
### Description:

Is this possible? I’d like to add this to my site to make publishing easier, and be able to access it online. 

Is there anything like this if not?

**Comment by ashmaroli** [comment]
@GiacomoLaw Unfortunately, this is not currently possible.

**Comment by mattr-** [comment]
this may be possible by proxying part of your site behind apache or nginx and setting it up require basic auth for the appropriate paths for jekyll admin. Basic auth is rather insecure though, so this may still not be the best idea.

**Comment by GiacomoLaw** [comment]
Okay, thanks. Guess I won't do it then, is there anything I can add which would allow me to do it?

Thanks

**Comment by mattr-** [comment]
No, sorry. We don't have anything built into the project for that at the moment.

**Comment by GiacomoLaw** [comment]
Okay, thanks for the help!
