### ISSUE TITLE
Publish without jekyll-admin

### ISSUE THREAD

**Issue by paulocoghi** [jekyll/jekyll-admin#490]
Hello, new user of Jekyll here. I would like to use Jekyll-Admin on my local machine to edit content, and publish only the static content on my server, without Jekyll-Admin.

Is it possible? Thanks!

**Comment by lexoyo** [comment]
Hi
Sure, you can put only _site to your server, that's where Jekyll builds the website

**Comment by paulocoghi** [comment]
Thanks!
