### ISSUE TITLE
Possible incompatibility with Jekyll 4.0.0

### ISSUE THREAD

**Issue by paulocoghi** [jekyll/jekyll-admin#491]
### Description:
It seems that jekyll-admin isn't proper configured to run with Jekyll 4.0.0.

### Tell us a bit about yourself:
* Version of JekyllAdmin: **v0.8.1**
* Version of Jekyll: possibly **v4.0.0** _(because `bundle show` also returns the same error)_
* Version of NodeJS: **v12.7.0**
* Operating System: **Ubuntu 18.04 64bits**

### Steps to reproduce:
After correctly installing Jekyll on my computer and running a test instance with no issues, I created the `_plugins` directory and installed **Jekyll Admin** through:

 - adding `  - jekyll-admin`to the "plugins" section on `_config.yml`
 - running `gem install jekyll-admin`
 - adding it to the `:jekyll_plugins` group in the Gemfile
 - and, finally, running `bundle install`
 - tried to run `bundle exec jekyll serve`

### I expected the following:
I expected to receive no errors, to be able to go to **`http://localhost:4000/admin`**

### But got the following, instead:
When running `bundle exec jekyll serve`, it returns:

```
Bundler could not find compatible versions for gem "jekyll":
  In snapshot (Gemfile.lock):
    jekyll (= 4.0.0)

  In Gemfile:
    jekyll (~> 4.0.0)

    jekyll-admin was resolved to 0.8.1, which depends on
      jekyll (~> 3.3)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

### Other details:
The error persists even after running **`bundle update`**

**Comment by mattboy9921** [comment]
I also have this issue. I've just tried using Bundler in a fresh folder to install Jekyll. Then, I add `gem 'jekyll-admin', group: :jekyll_plugins` to my Gemfile and get the same error as OP when running `bundle install`. Only difference is mine says `jekyll-admin was resolved to 0.1.1, which depends on jekyll (~> 3.1)`.

**Comment by paulocoghi** [comment]
@mattboy9921 , I tried to update Jekyll Admin using `bundle update` to see if a newer version would be compatible with Jekyll 4.0.0.

This is possibly the reason that my last error informs the version `0.8.1` to Jekyll Admin instead of `0.1.1`

**Comment by ashmaroli** [comment]
Yes @mattboy9921 you're correct.
`~> 3.3` means *allow all versions in the `3.x` series starting from `3.3.0`*
However, `~> 3.3.0` would mean *allow only versions in the `3.3.x` series starting from `3.3.0`*

**Comment by derekhe** [comment]
Please help to support 4.0

**Comment by lexoyo** [comment]
It should be well tested but I believe we just need to add something like `, ">= 4.0.0"` in the gemfile. Would someone do a Pull Request? I can help you with the git part maybe?

**Comment by ashmaroli** [comment]
Guys, there's already a PR for this: #492 
Unlike other plugins in the Jekyll ecosystem, this plugin contains a "front end" version based on ReactJS and Node modules which are compiled at release (or while testing).

So, you need to build the gem from source with the required Node modules and can't just point your Gemfile to the GitHub repo and expect it to work..

**Comment by lexoyo** [comment]
My bad, I'll make a review now

**Comment by shanebdavis** [comment]
> Guys, there's already a PR for this: #492

What is blocking on this PR getting accepted? I have some time to commit to open-source. I'd be happy to help out to get jekyll-admin updated for jekyll 4.0. @benbalter @mertkahyaoglu @ashmaroli 

Thanks for the great project! Hope I can help bring it up-to-date.
-Shane

**Comment by ashmaroli** [comment]
`jekyll-admin-0.9.0` with support for Jekyll 4.0 has been released.
