### ISSUE TITLE
Support for default meta fields

### ISSUE THREAD

**Issue by strzibny** [jekyll/jekyll-admin#581]
I have a blog where I follow the standard `2020-02-16-blog-post.md` post paths, but the permalink is actually without the date (and included as `permalink` in meta):

e.g. `2020-02-16-blog-post.md`  shows at `/blog-post/`.

Is there some way to teach jekyll-admin that the preview is found at the correct (`permalink`) address? And possibly let jekyll-admin to also autogenerate this correct permalink?

**Comment by strzibny** [comment]
Okay, it seems that the previews are actually working. So the question that remains is how to automate the `permalink` field or in generall other metadata like `layout` to `post` so I don't have to add it manually with each post?

**Comment by ashmaroli** [comment]
Please refer Jekyll documentation on this feature:
https://jekyllrb.com/docs/configuration/front-matter-defaults/

**Comment by strzibny** [comment]
@ashmaroli Thank you. I could solve it with default Jekyll settings, sorry for the noise!
