### ISSUE TITLE
Is default, editable metadata on a new document possible?

### ISSUE THREAD

**Issue by i-a-n** [jekyll/jekyll-admin#596]
Hi, basic question here: is it not possible to specify an array of "default" editable metadata/frontmatter fields when creating a new document? For instance, let's say I have a collection entitled `faculty_members`:

`_config.yml`
```yaml
collections:
  faculty_members:
    output: true
```

and every `faculty_member`, has the same front matter, like so:

`/_faculty_members/FooBar.md`
```yaml
---
name: Foo Bar
department: Baz
---
Foo Bar is the head of Baz.
```
when I click New Document in `Faculty_members`...
![Screen Shot 2020-04-29 at 8 37 02 PM](https://user-images.githubusercontent.com/1937355/80669431-46a28580-8a59-11ea-8eda-d00566ff6a4f.png)

...is there really no way to have `department` automatically added as a metadata field at the bottom of the new document form? I attempted a few different things, including adding default values to the `_config.yml`, but these fields became read-only and I couldn't edit them, making them useless for this.

I see a few other issues that seem to mention this idea, I _think_, but they all seem to have been closed or ignored, like https://github.com/jekyll/jekyll-admin/issues/464. Am I missing something vital? This seems like a very, very basic ask and is it really impossible?

Thanks for your time.

**Comment by ashmaroli** [comment]
When you set default front matter in the config file, it is rendered as a *read-only* key in the view.
However, you can override the value by redefining the value in the *editable* inputs.

**Comment by i-a-n** [comment]
> When you set default front matter in the config file, it is rendered as a _read-only_ key in the view.
> However, you can override the value by redefining the value in the _editable_ inputs.

Thanks for the quick response @ashmaroli, good to know there's a workaround. However, I do think this UX could be improved upon by simply having the default fields be editable upfront. Is there any technical reason why this wouldn't be preferable?

If there isn't, would you be open to a PR to make those fields editable?

**Comment by ashmaroli** [comment]
I kept the defaults *read-only* so that it doesn't propagate into the document when it is written to disk. (You can downgrade to `v0.9.0` for that UX for the time being if you want..)

To have the defaults editable yet propagate just the changed set needs some :thinking: ... ...
Lets see..

**Comment by i-a-n** [comment]
> I kept the defaults _read-only_ so that it doesn't propagate into the document when it is written to disk. (You can downgrade to `v0.9.0` for that UX for the time being if you want..)
> 
> To have the defaults editable yet propagate just the changed set needs some 🤔 ... ...
> Lets see..

Oh, I understand the problem now. Also, thanks for letting me know about the `0.9.0` version, I'll use that one for right now.

Only propagating the changed defaults sounds like it would be error-prone and expensive to do the obvious way (checking against the defaults in the config file every time a document is saved). I might recommend something much simpler and dumber: making the user decide whether to edit a default:

![checkbox](https://user-images.githubusercontent.com/1937355/80684764-081dc280-8a7b-11ea-8a1b-a928f37c1bb7.gif)

... And then when a document is saved, any default with a checked box is submitted, any default without one is not.

Just one option, something to think over. I'm also happy to help implement any javascript part of the code, if you decide it's a good idea (and I can figure out how to set up a dev environment). Thanks again.

**Comment by ashmaroli** [comment]
I'm on-board with the idea. :+1: 
You're welcome to take a stab at implementing it.

**Comment by i-a-n** [comment]
hey @ashmaroli, wondering if you wouldn't mind giving your feedback if you have a moment. here's what I came up with:

![override-revert](https://user-images.githubusercontent.com/1937355/80930222-f122ed00-8d66-11ea-8cee-518815014c54.gif)

I have it so the defaults first render disabled/grayed out, and the menu option exists to "override default". when clicked, the field is added to the `metadata: { metadata: {} }` redux store and can be edited/submitted as a typical field. it can also be "reverted" back to the default key/value.

defaults that have been overridden and saved will render like normal fields, but they too have the option to be reverted to the default (whatever's in `default_front_matter`).

there is no change to additional, non-default fields that get added.

let me know if you like this flow or have any other input, if you like it I'll clean it up, write tests and commit/submit it. thanks.

**Comment by ashmaroli** [comment]
The preview looks great!! I :heart: it!
Does the overrides carry over to the written page as expected?

Either ways, open the pull request when you're ready. We can continue this discussion on that thread.
