### ISSUE TITLE
Is it possible to browse at https:// ~

### ISSUE THREAD

**Issue by magicmanji** [jekyll/jekyll-admin#598]
This is a very useful plugin. Therefore, it is not a problem but a request or question. I use Jekyll only for generating html etc., the web server uses apache2, and I have also introduced ssl. Then Jekyll-admin, which was able to browse on http, cannot be browsed on https. In other cases, the contents can be viewed without any problem. Is it possible to browse at https://xxx/admin?

**Comment by ravigupta-art** [comment]
I think what you want and refer has been covered in these previous issues #414 and #417 .
As they mentioned they are looking for contribution to the project, and because of this lack of contribution, maybe we won't be able to see this feature soon.

**Comment by mertkahyaoglu** [comment]
Thanks @magicmanji. As @ravigupta-art explained, currently we cannot allocate enough time to add this feature in the short term.
