### ISSUE TITLE
I can't enable draft option in jekyll admin sidebar

### ISSUE THREAD

**Issue by Grifo89** [jekyll/jekyll-admin#600]
I'm trying to figured out how to add draft option in the sidebar but I can't find how. I appreciate the help.

**Comment by ashmaroli** [comment]
It should render automatically if there are drafts in the site.
Have you enabled `drafts` for the Jekyll site? Either via config file or via the terminal:
```
bundle exec jekyll serve --drafts
```

**Comment by Grifo89** [comment]
Yes, it works! Thank you!! @ashmaroli

**Comment by vcavallo** [comment]
This isn't working for me. i'm runnning jekyll serve with `--drafts` (and I do see the items in `_drafts` on the served site) but the /admin interface doesn't show drafts anywhere. Furthermore, I have this in my _config.yml:

```
jekyll_admin:
  show_drafts: true
  homepage: "posts"

```

For what it's worth, the homepage isn't rendering "posts" but the default "pages", and the "Error could not fetch the config" message still appears (but the "configuration" item in the sidebar does show my current _config.yml

**Comment by vcavallo** [comment]
Okay, fixed it. I needed to  have `show_drafts: true` in my top level config:

```
show_drafts: true
jekyll_admin:
  # hidden_links:
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"
```

**Comment by vcavallo** [comment]
Problem with that is the drafts show up on the live site...

**Comment by chr0nikler** [comment]
+1 just had this issue, looks like `--drafts` option locally is no longer applying the same logic as the `show_drafts` config, which affects live site.

**Comment by chr0nikler** [comment]
Opened https://github.com/jekyll/jekyll-admin/issues/714
