### ISSUE TITLE
Old topic: password protection

### ISSUE THREAD

**Issue by sixtyfive** [jekyll/jekyll-admin#627]
Hi all, looking through old Issues (2016 to 2017 ish) it seems back then lots of people were interested in being able to use jekyll-admin on the server. There was discussion about what would have to be done for that, pros and cons, etc. But the one thing that would make it "good enough", being able to have username/password protection, was never implemented. Unless I missed it, there was also never a PR wrt this. It's 2021 now. Would such a PR be welcome or still just evaporate on the hot stone of wanting to achieve a solid 1.0?

**Comment by y377** [comment]
use nginx/apache Password verification function

**Comment by y377** [comment]
At the same time, using SSL certificate authentication is more secure than any password authentication

**Comment by mertkahyaoglu** [comment]
@sixtyfive Hi there. Unfortunately we are not going to implement this since Jekyll Admin is meant to work locally. You can try what @y377 suggested though.
