### ISSUE TITLE
Document indexes shouldn't include document content

### ISSUE THREAD

**Issue by benbalter** [jekyll/jekyll-admin#63]
Otherwise, on a large site, with a lot of posts, the `/posts/` endpoint would be extremely large.

**Comment by benbalter** [comment]
@mertkahyaoglu would this cause a problem if the document index didn't return the `content` or `raw_content` fields? I assume an individual page view calls the individual page's endpoint?

**Comment by mertkahyaoglu** [comment]
> I assume an individual page view calls the individual page's endpoint

Yes, that's correct. We don't need them other than individuals' endpoints.
