### ISSUE TITLE
Improve README and getting started experience for developers

### ISSUE THREAD

**Issue by jldec** [jekyll/jekyll-admin#67]
It would be awesome if other developers who want to get involved could run jekyll-admin in a debug/development mode to help repro issues, offer PR feedback, or implement fixes. 

The README is just a little too terse right now to make this straightforward.

missing are
- how to generate the UI (minified or unminified for debugging)
- basic configuration/assumptions: (how jekyll-admin knows what site to serve)
- how to install and run the plugin on a local jekyll site (in debug and non-debug mode)

**Comment by benbalter** [comment]
Some info in https://github.com/jekyll/jekyll-admin/tree/master/docs, although, I don't think it's linked.

**Comment by jakebruemmer** [comment]
This is something that I would like to see as well. I was able to install jekyll-admin on my local computer and then run the node server and access it in the browser, but then I wasn't really sure where to go from there in terms of working on contributing to the project. @jldec Is this something that you'd be interested in putting together with me?

**Comment by mertkahyaoglu** [comment]
I guess we can close this now :+1:
