### ISSUE TITLE
Gem not updated for one and half years

### ISSUE THREAD

**Issue by kebugcheckex** [jekyll/jekyll-admin#687]
### Description:
The latest release shown on [GitHub](https://github.com/jekyll/jekyll-admin) and [RubyGems.org](https://rubygems.org/gems/jekyll-admin) are both v0.11.0. They have not been updated for one year and half by now (June 2022). There are updates to the code since the last release. Is this updated by some CI systems or is it updated manually by someone?

I'm asking because Github keeps telling me that there are vulnerabilities due to dependencies `rack` and `sinatra`. They have been fixed in the latest code but the changes are not pushed to RubyGems.org. Thus `bundle install` is still pulling the version from December 2020.

**Comment by mzjp2** [comment]
Ditto.

**Comment by coreycarvalho** [comment]
Yep, there should definitely be a new release of this gem.

**Comment by alanlivio** [comment]
Hello. I really appreciate the plugin. But this lack of update is indeed an issue.
It would be very nice if the admin @jakebruemmer and @benbalter say something.

**Comment by ashmaroli** [comment]
I have released v0.11.1 with relaxed constraints on the `sinatra` framework.
