### ISSUE TITLE
Advice for extending jekyll-admin?

### ISSUE THREAD

**Issue by derek-adair** [jekyll/jekyll-admin#690]
There are features I would like from this project and am willing to put the work in to do so.  However, I am not a ruby dev so its not exactly clear how I might go about extending this project and making it my own.  I am fine with this [projects scope](https://github.com/jekyll/jekyll-admin/issues/209), but it is not immediately clear how I might extend this without a fork.

Would it be possible to override css or javascript to bend this to my will without publishing my own gem?

Am I forced to fork and run [gemstash](https://guides.rubygems.org/run-your-own-gem-server/)?

Could there be some case to be made for jekyll-admin plugins?

Thanks for your time.

**Comment by ashmaroli** [comment]
@derek-adair Unlike other plugins from the Jekyll organization, Jekyll Admin is not extensible.
You will have to fork it, set up a dev environment (Node JS), make necessary changes, and build the front end. If the changes made are only for your local usage, you need not cut a gem and manage a private gem server. The front end built above will be accessible to the local jekyll server through Bundler and Gemfile.
