### ISSUE TITLE
Markdown edit box is writing rendered HTML, not raw markdown

### ISSUE THREAD

**Issue by benbalter** [jekyll/jekyll-admin#79]
E.g.:

![screen shot 2016-07-28 at 11 43 10 am](https://cloud.githubusercontent.com/assets/282759/17219185/77e96bca-54b8-11e6-803c-9964306fe590.png)

Steps to reproduce:

1. Navigate to http://localhost:4000/admin/pages/page.md
2. Modify the markdown
3. Hit save

Expected:

Update markdown is saved and displayed

Actual:

* `<h1 id="test-page">Test Page</h1>` is saved to disk and displayed.
* `raw_content` metadata filed is saved with the content

@mertkahyaoglu this may be a miscommunication / need to change on the server side. I'm guessing you're sending `raw_content` as a metadata field, in addition to `body`?

**Comment by mertkahyaoglu** [comment]
This is fixed with #59. You can see it [here](https://github.com/jekyll/jekyll-admin/blob/274c496b906f1e92e22a87d656a6dd4d3e1a8f3e/lib/jekyll-admin/public/src/actions/pages.js#L52).

**Comment by benbalter** [comment]
I think this may be my fault / miscommunication via https://github.com/jekyll/jekyll-admin/issues/82.

If that proposal looks right, then the edit box should just pull from and push to `raw_content` (and the front matter below can just look at what's in `front_matter` without any need to hard code any omitted keys).

**Comment by mertkahyaoglu** [comment]
Actually that `metadata` I'm omitting `raw_content` from is an internal redux state which stores all of the fields which are editable (title, path, raw_content and metafields at the bottom). This way I can keep track of what's changed. That might be a bad naming though.
