### ISSUE TITLE
Don't save empty metadata fields

### ISSUE THREAD

**Issue by benbalter** [jekyll/jekyll-admin#81]
Steps to reproduce:

1. Navigate to http://localhost:4000/admin/pages/page.md
2. Edit a metadata field
3. Hit save

Expected:

No new fields added

Actual:

"New field 1", "New field 2", "New field 3", etc. added to the front matter, even if they have no content.

**Comment by benbalter** [comment]
@mertkahyaoglu is this still the case? If an easy fix, would be great to close this before the initial release.

**Comment by mertkahyaoglu** [comment]
Yep, that's in my mind. Now working on it 👍
