### ISSUE TITLE
Payload for API Requests

### ISSUE THREAD

**Issue by benbalter** [jekyll/jekyll-admin#82]
Looking at #79, #80, and #81, I think there's some ambiguity in terms of how to describe a document when making requests to and getting responses from the API. At least part of this is my fault, with the late addition of `raw_content` and `front_matter` fields via #61 and #53.

Whatever we do, I think it makes sense for the response and the request to be consistent.

Here's what I'd like to propose as the document (page, post, etc.) payload, and if it sounds good, I'll document it more formally:

* Top level keys are keys with special meaning. This includes:
  * Computed, read-only keys like `url`
  * Computed, read/write keys like `path`
  * Front matter defaults
* The top-level namespace will have `content` and `raw_content` keys with the HTML and markdown respectively
* The top-level namespace will have a `front_matter` key which includes the raw front matter as seen on disk.

A standard page may then look like this:

```json
{  
   "some_front_matter":"default",
   "foo":"bar",
   "content":"<h1 id=\"test-page\">Test Page</h1>\n",
   "dir":"/",
   "name":"page.md",
   "path":"page.md",
   "url":"/page.html",
   "raw_content":"# Test Page\n",
   "front_matter":{  
      "foo":"bar"
   }
}
```

When making a request, clients can set the following top-level fields:

* `raw_content` - the raw, unrendered content to be written to disk (currently `body`)
* `front_matter` - the entire YAML front matter object to be written to disk (currently `meta`)
* `path` - the new file path relative to the site source, if the file is to be renamed

Does that make sense? Anything I'm missing? If so, will change the API to use `raw_content` and `front_matter` rather than `body` and `meta` and will update the docs accordingly.

**Comment by mertkahyaoglu** [comment]
@benbalter It makes sense. With #59, front-end exactly follows this propose. 👍  for `raw_content` and `front_matter`.
