### ISSUE TITLE
Server throws `undefined method 'to_api'` if PUT request payloads have an empty `front_matter`

### ISSUE THREAD

**Issue by mertkahyaoglu** [jekyll/jekyll-admin#91]

**Comment by benbalter** [comment]
@mertkahyaoglu I'm having trouble recreating this... could you paste a `cURL` request that fails?

**Comment by mertkahyaoglu** [comment]
`curl -X PUT -d '{"path":"test10.md", "raw_content":"# test", "front_matter":{}}' http://localhost:4000/_api/pages/test10.md`

It creates the requested page though.
