### ISSUE TITLE
Show post date in post index list

### ISSUE THREAD

**Issue by benbalter** [jekyll/jekyll-admin#95]
It'd be nice to show the date of posts for the post list (and to sort reverse chronologically by date, which we can do on the API level, if you want).

Other collections could theoretically have dates, but there's no programatic way to tell, so I think it's fine just to do this for posts for now.

**Comment by mertkahyaoglu** [comment]
This [commit](https://github.com/jekyll/jekyll-admin/pull/93/commits/e85c6e298bead98b153bd4d33c0fcfe46d388440) implements showing the date of documents in index list. I will create a PR for sorting.

**Comment by mertkahyaoglu** [comment]
Just noticed that other collections' dates are the start date of the server 😬
