### ISSUE TITLE
jekyll-admin gem can not be installed

### ISSUE THREAD

**Issue by scipv** [jekyll/jekyll-admin#98]
Hi, 
I'm trying to add jekyll-admin to a jekyll blog.
I added the gem in Gemfile and in _config.
When I give bundle install the following error is display.
What can I do in order to install jekyll-admin?

```
Fetching gem metadata from https://rubygems.org/                                                                                                                                 
Fetching version metadata from https://rubygems.org/                                                                                                                             
Fetching dependency metadata from https://rubygems.org/                                                                                                                          
Could not find gem 'jekyll-admin' in any of the gem sources listed in your                                                                                                       
Gemfile or available on this machine.    
```

**Comment by DirtyF** [comment]
`jekyll-admin` gem has not been released yet, but you can take a look at it and follow the insctructions mentioned in https://github.com/jekyll/jekyll-admin/blob/master/docs/development.md

**Comment by scipv** [comment]
Please specify somewhere in the documentation that the jekyll-admin is not released. Sorry for the question then

**Comment by mertkahyaoglu** [comment]
I think #56 will do the job.

**Comment by caspervonb** [comment]
Time to close this, as the gem has been published.

**Comment by benbalter** [comment]
Thanks @caspervonb and @scipv for reporting. Please let us know if you're still having trouble in a new issue.
